---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
#  dependsOn:
#    - name: local-path-provisioner
#      namespace: storage
#    - name: volsync
#      namespace: volsync
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker

    controllers:
      unifi:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            nameOverride: *app
            image:
              repository: jacobalberty/unifi
              tag: v9.2.87@sha256:150ab9668d3101d0c3762db920a7925082faafa0bead810fafd0713ac1a7b7c6
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              RUNAS_UID0: "false"
              UNIFI_UID: "999"
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              # JVM_INIT_HEAP_SIZE: null
              JVM_MAX_HEAP_SIZE: 1024M
            resources:
              requests:
                memory: 2Gi
                cpu: 50m
              limits:
                memory: 3Gi
            probes:
              liveness:
                enabled: true
                port: 8080
              readiness:
                enabled: true
                port: 8080
              startup:
                enabled: true
                port: 8080
#        statefulset:
#          volumeClaimTemplates:
#            - name: config
#              accessMode: ReadWriteOnce
#              size: 10Gi
#              storageClass: local-hostpath
#              globalMounts:
#                - path: /unifi
    service:
      app:
        controller: *app
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: ${SVC_UNIFI_ADDR}
        ports:
          http:
            port: 8443
            protocol: HTTPS
          controller:
            enabled: true
            port: 8080
            protocol: TCP
          portal-http:
            enabled: false
            port: 8880
            protocol: HTTP
          portal-https:
            enabled: false
            port: 8843
            protocol: HTTPS
          speedtest:
            enabled: true
            port: 6789
            protocol: TCP
          stun:
            enabled: true
            port: 3478
            protocol: UDP
          syslog:
            enabled: true
            port: 5514
            protocol: UDP
          discovery:
            enabled: true
            port: 10001
            protocol: UDP
    ingress:
      app:
        enabled: true
        className: "internal"
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.davidstewen.com
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
#          nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
          hajimari.io/icon: mdi-lan
          hajimari.io/group: Home
          hajimari.io/appName: Unifi Network Controller
          hajimari.io/url: https://unifi.${SECRET_DOMAIN}
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host

    persistence:
      data:
        enabled: true
        existingClaim: unifi-config
        globalMounts:
          - path: "/unifi"
