---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app unifi
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
#  dependsOn:
#    - name: local-path-provisioner
#      namespace: storage
#    - name: volsync
#      namespace: volsync
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker

    controllers:
      app:
        type: deployment
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsUser: 999
            runAsGroup: 999
            fsGroup: 999
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            nameOverride: *app
            image:
              repository: jacobalberty/unifi
              tag: v9.3.45@sha256:6f1cc8eeda6a2303a3939f8f6565d4e4ca963b18b2d5dfae7e1ed4799d102eeb
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
              RUNAS_UID0: "false"
              UNIFI_UID: "999"
              UNIFI_GID: "999"
              UNIFI_STDOUT: "true"
              # JVM_INIT_HEAP_SIZE: null
              JVM_MAX_HEAP_SIZE: 1024M
            resources:
              requests:
                memory: 512Mi
                cpu: 100m
              limits:
                memory: 2Gi
            probes:
              liveness:
                enabled: true
                port: 8080
              readiness:
                enabled: true
                port: 8080
              startup:
                enabled: true
                port: 8080
#        statefulset:
#          volumeClaimTemplates:
#            - name: config
#              accessMode: ReadWriteOnce
#              size: 10Gi
#              storageClass: local-hostpath
#              globalMounts:
#                - path: /unifi
    service:
      app:
#        controller: *app
        type: LoadBalancer
        externalTrafficPolicy: Cluster
        annotations:
          external-dns.alpha.kubernetes.io/hostname: unifitalos.davidstewen.com
          lbipam.cilium.io/ips: "10.200.15.227"
        ports:
          http:
            primary: true
            port: 8080
            protocol: HTTP
          stun:
            port: 3478
            protocol: UDP
          https:
            port: &port 8443
            protocol: HTTPS
          secure-redirect:
            port: 8843
            protocol: HTTPS
          http-redirect:
            port: 8880
            protocol: HTTP
          speedtest:
            port: 6789
            protocol: TCP
          unifi-disc:
            port: 10001
            protocol: UDP
          unifi-disc-12:
            port: 1900
            protocol: UDP
          syslog:
            protocol: UDP
            port: 5514
#    ingress:
#      app:
#        enabled: true
#        className: "internal"
#        annotations:
#          external-dns.alpha.kubernetes.io/target: internal.davidstewen.com
#          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
##          nginx.ingress.kubernetes.io/proxy-ssl-verify: "off"
#          hajimari.io/icon: mdi-lan
#          hajimari.io/group: Home
#          hajimari.io/appName: Unifi Network Controller
#          hajimari.io/url: https://unifi.${SECRET_DOMAIN}
#        hosts:
#          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
#            paths:
#              - path: /
#                service:
#                  identifier: app
#                  port: http
#        tls:
#          - hosts:
#              - *host

    route:
      app:
        hostnames: ["unifitalos.davidstewen.com"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port
            timeouts:
              request: 0s  # websocket, never time out
              backendRequest: 0s  # websocket, never time out

    persistence:
      data:
        enabled: true
        existingClaim: unifi-config
        globalMounts:
          - path: "/unifi"
