---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-budget-exporter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: actual-budget-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ACTUAL_SERVER_URL: "{{.ACTUAL_SERVER}}"
        ACTUAL_PASSWORD: "{{.ACTUAL_PASSWORD}}"
        ACTUAL_BUDGET_ID_1: "{{.ACTUAL_SYNC_ID}}"
  dataFrom:
    - extract:
        key: actual
