---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
#        PLUS_API_KEY: "{{ .PLUS_API_KEY }}"
        # Mosquitto Connection
        FRIGATE_MQTT_USERNAME: "{{ .FRIGATE_MQTT_USERNAME }}"
        FRIGATE_MQTT_PASSWORD: "{{ .FRIGATE_MQTT_PASSWORD }}"
        # Camera Details
        FRIGATE_RTSP_HOST_PHONE_IP: "{{ .FRIGATE_RTSP_HOST_PHONE_IP }}"
        FRIGATE_RTSP_USER_PHONEAPP: "{{ .FRIGATE_RTSP_USER_PHONEAPP }}"
        FRIGATE_RTSP_PASSWORD_PHONEAPP: "{{ .FRIGATE_RTSP_PASSWORD_PHONEAPP }}"
        FRIGATE_RTSP_HOST_WYZE3: "{{ .FRIGATE_RTSP_HOST_WYZE3 }}"
        FRIGATE_RTSP_USER_WYZE3: "{{ .FRIGATE_RTSP_USER_WYZE3 }}"
        FRIGATE_RTSP_PASSWORD_WYZE3: "{{ .FRIGATE_RTSP_PASSWORD_WYZE3 }}"
  dataFrom:
    - extract:
        key: frigate
