---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: frigate
  namespace: home
  labels:
    app.kubernetes.io/name: &name frigate
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
