# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/probe_v1.json
---
kind: Probe
apiVersion: monitoring.coreos.com/v1
metadata:
  name: devices
spec:
  module: icmp
  prober:
    url: blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      static:
        - nas.davidstewen.com
#        - garage-door.internal
        - hdhomerun.davidstewen.com
#        - idrac.internal
#        - kiosk.internal
#        - kvm.internal
#        - pikvm.internal
        - receiver.internal
        - ups.davidstewen.com
        - vacuum.davidstewen.com
#        - zigbee-controller.internal
#        - zwave-controller.internal
