---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gameserver
components:
  - ../../components/common
resources: []
  # Flux-Kustomizations1
#  - ./minecraft/ks.yaml
