---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-machine-learning
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  dependsOn:
    - name: immich-server

  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: &configMap immich-configmap
          secret.reloader.stakater.com/reload: &secret immich

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v2.0.1-openvino@sha256:1a5a49530275ee49553b8135646631c64b62e7d22614004db8f765013761b0ba

            env:
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload

            envFrom:
              - secretRef:
                  name: *secret
              - configMapRef:
                  name: *configMap

            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 100m
                memory: 6000Mi
              limits:
                gpu.intel.com/i915: 1

    service:
      main:
        controller: main
        ports:
          http:
            port: 3003

    persistence:
      library:
        existingClaim: immich-upload-pvc
        globalMounts:
          - path: /usr/src/app/upload
      cache:
        existingClaim: immich-machine-learning-cache
        globalMounts:
          - path: /cache
      geocoding-dump:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.reverse-geocoding-dump
      transformers-cache:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.transformers_cache
