---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-server
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://bjw-s.github.io/helm-charts
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
#    defaultPodOptions:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: kubernetes.io/arch
#                operator: In
#                values:
#                - arm64
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 50
#            preference:
#              matchExpressions:
#              - key: node-role.kubernetes.io/worker
#                operator: In
#                values:
#                - worker
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: &configMap immich-configmap
          secret.reloader.stakater.com/reload: &secret immich

        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.5.0

            envFrom: &envFrom
              - configMapRef:
                  name: *configMap
              - secretRef:
                  name: *secret

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.135.3@sha256:df5bbf4e29eff4688063a005708f8b96f13073200b4a7378f7661568459b31e9
#            args: ["start-server.sh"]

            env:
              IMMICH_MEDIA_LOCATION: &mediaLocation /usr/src/app/upload

            envFrom: *envFrom

            resources:
              requests:
                cpu: 100m
                memory: 250Mi

        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

    service:
      main:
        controller: main
        ports:
          http:
            port: &httpPort 2283

    ingress:
      main:
        className: internal
        annotations:
#          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
          hajimari.io/appName: Photos
          hajimari.io/icon: heroicons:photo
          hajimari.io/instance: "admin"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Media
          gethomepage.dev/name: Immich
          gethomepage.dev/icon: immich.png
          gethomepage.dev/description: Self-hosted photo and video management solution
#          gethomepage.dev/widget.type: immich
#          gethomepage.dev/widget.url: http://immich-server.media.svc.cluster.local:3001
#          gethomepage.dev/widget.key: "f8J3C8v9xUBrxTixovnoGeOoKUCdgFKj7DVtubfwY"
        hosts:
          - host: &host "photos.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: *httpPort
        tls:
          - hosts:
              - *host

    persistence:
      config:
        type: configMap
        name: *configMap
        globalMounts:
          - path: /config

      library:
        existingClaim: immich-upload-pvc
        globalMounts:
          - path: *mediaLocation

      geocoding-dump:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.reverse-geocoding-dump

      transformers-cache:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.transformers_cache
