---
apiVersion: nfd.k8s-sigs.io/v1alpha1
kind: NodeFeatureRule
metadata:
  name: vlan-iot-device
spec:
  rules:
    - # IOT VLAN
      name: vlan.iot
      labels:
        node.network/vlan-iot: "true"
      matchFeatures:
        - feature: network.virtual
          matchExpressions:
            name: { op: In, value: ["enp6s19"] }
            #name: { op: InRegexp, value: ["(enp0s31f6|enp1s0).20$"] }
            # This should really be a regex, but sometimes
            # it matches on lxc virtual devices created by
            # kubernetes (cilium?)
    #            name: { op: InRegexp, value: [".20$"] }
