---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cnpg-backup17
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      postgres-backup:
        type: cronjob
        cronjob:
          concurrencyPolicy: Forbid
          schedule: "0 17 * * *"
        pod:
          restartPolicy: OnFailure
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
        containers:
          app:
            image:
              repository: docker.io/prodrigestivill/postgres-backup-local
              tag: 18@sha256:f70742ebe42b2277689b028d1fd15aa80f77cffa01da163cc9f85a6ff1866e7f
            command:
              - /bin/bash
              - -x
              - /backup.sh
            env:
              - { name: TZ, value: "${TIMEZONE:=Etc/UTC}" }
              - { name: POSTGRES_DB, value: "app,atuin,authentik,firefly,home_assistant,lldap,openwebui,radarr_main,vaultwarden" }
              - { name: POSTGRES_HOST, value: "postgres-ro.database.svc.cluster.local" }
              - { name: POSTGRES_PORT, value: 5432 }
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: cloudnative-pg-secret
                    key: username
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: cloudnative-pg-secret
                    key: password
    persistence:
      nas:
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/postgres/postgres17/backups
        globalMounts:
          - path: /backups
            readOnly: false
