---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming-whisper
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  interval: 10m0s
  values:
    controllers:
      wyoming-whisper:
        containers:
          app:
            image:
              repository: rhasspy/wyoming-whisper
              tag: 2.5.0
              pullPolicy: Always
            env:
              TZ: ${TIMEZONE}
            args:
              - --model
                # tiny-int8 (43 MB)
                # tiny (152 MB)
                # base-int8 (80 MB)
                # base (291 MB)
                # small-int8 (255 MB)
                # small (968 MB)
                # medium-int8 (786 MB)
                # medium (3.1 GB)
              - small
              - --language
              - en

            resources:
              requests:
                cpu: 500m
                memory: 250Mi

        strategy: Recreate
    service:
      app:
        controller: wyoming-whisper
        ports:
          tcp:
            port: 10300
            protocol: TCP
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /data
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
