---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming-whisper
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      wyoming-whisper:
        containers:
          app:
            image:
              repository: rhasspy/wyoming-whisper
              tag: 3.0.1
              pullPolicy: Always
            env:
              TZ: ${TIMEZONE}
            args:
              - --model
                # tiny-int8 (43 MB)
                # tiny (152 MB)
                # base-int8 (80 MB)
                # base (291 MB)
                # small-int8 (255 MB)
                # small (968 MB)
                # medium-int8 (786 MB)
                # medium (3.1 GB)
              - small
              - --language
              - en

            resources:
              requests:
                cpu: 500m
                memory: 250Mi

        strategy: Recreate
    service:
      app:
        controller: wyoming-whisper
        ports:
          tcp:
            port: 10300
            protocol: TCP
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /data
    defaultPodOptions:
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
