---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backup16
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: cnpg-backup16-secret
    template:
      data:
        POSTGRES_HOST: "postgres17-rw.database.svc.cluster.local"
        POSTGRES_USER: "{{ .POSTGRES_SUPER_USER }}"
        POSTGRES_PASSWORD: "{{ .POSTGRES_SUPER_PASS }}"
        POSTGRES_PORT: "5432"
  dataFrom:
    - extract:
        key: cloudnative-pg
