apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ZZzQBDuJp0nzXbfOgnabOThd9dFaQokRVQZc+gBcmhyc025H,iv:r1biO3+M9Zvi6awZeE7mmI1srrf5DkrqvpY0bQfPHl4=,tag:892mAAomoV5jppzXD6JL9w==,type:str]
    credentials.json: ENC[AES256_GCM,data:AOeHzIe9b9b4qR3hWGzeBdPl6TI5HuBfQx6uNk8vsdavNC04xu3EV3roz1yAXAwI2k7u+r1TW1Cz9l3kG9X/qgIOHty20Xsl7GYIoyqQTWT0jFtV7rwEk81ABsob4g1EFiwfuIHqOeFO5h2PLqcQ6EGL4hTGZMAT3GNhF/xfcF2+SvXCnF0vdNvOmMMSXwBMseuqIYuVK437HvV/b8vu+4EUcHLsX1BwTYljLsb8fw==,iv:NqKLsx5LByepjhOFEsqIaOUxS9lvqPYzOG+7AQ+1txk=,tag:MOHFA5v43jvUjHDRhUtltg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLWlMyMy9xYUlIL0pIQUxw
            K2xkaTJ2Y2RNNkcyZk4zRTdhU3ljOHVjWjNvCmVYY3d0dEpJeGJUWW96bmRVQ214
            dHUwb1dmVS9kUm0yajNDWC8rT0ZRZG8KLS0tIGExTXAzUEpWM1djdFluYk8xVXZ4
            MmhtQkZIU1hSRXhid2JRNHVaMEtzNGcKwm7OR8d5Q0jovDXVaZErhGD6XI+7q830
            32M5HFtJYynuimRuAmMVk9dI9h90LJG0QAqvMxmKR6GIIqwcS0JIRA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T10:08:55Z"
    mac: ENC[AES256_GCM,data:6kk/hWXDmOPUDFsf88ENUNKO+nvxI6c0MG1Sktkix9r4LIRSZ7ri+G9FiNP3MKxWbybfIqWh0XZ1jQZ8Dehv5ZF6orcvGRWwCxtm33g5q0B9mTVJ2XG6z0/7hlWpeEQ4E6JazMKl8EJ5O4S+/FnV6YMG+zjMR25hnGN7bzHUt8s=,iv:/YZiQvEml5ukBK7g1c70NiIPJ7NaCq7Z7e2FURZKiQI=,tag:BSMYF6ZBg7SB5rwvt6Pqow==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
