apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:qEdcYHfds8oGI9aXoQ3graTCOCam0IqoCYrv2cqQJqX9BDqI,iv:G3GagA6PZUEsJ0lJ8Irfvcndoq551PJ3ARhqOVLxurI=,tag:cT6/HbQbGWGmx0ax1f/xUw==,type:str]
    credentials.json: ENC[AES256_GCM,data:RWpRipKXqZ3c93PwV5UibZlrKop3v8Rawz7VN8mo9175DtGNocjuBvVlQeYWkEPmGbKIPlq95jHpYX8+0zJnZSL6cPP2FUEYHzySe1OilakjVUQ5cRLM9LX8WZ+szozKqbocK0O/rcnNXNxWRhhQIm665PurZHe0Oz2LXPIjRf0OpAzgMzGPpvE25gSa2LX0ath/L/i1v4V1Jih58etz+CjWj9/pbzO3CFOfY7JCjA==,iv:+vs4VrMYGL/MjKBBVF+I07oEfzEnr13gX98GVwYYjpk=,tag:rX21e3oHHDeUHc82eUTMHw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvOTV2U1pXY1FwWmI3Y0dx
            RWJnWlZCMzdmMGlETkpmOXUwYlppRjFmUjFVCmE2Unp2MlN2SmZMam0xVmdwV01Z
            OWlmTEJCcEpRT3VRaWVyOFFkakVad2MKLS0tIFBCZGxSYSs1eFVidlR1TklVZmVz
            Q29WT0FzOE9uaXRxWHJsMCtoYUFvS3cK3bUkEJIWsFSybFIKQMWa8o1wlQ5CY9fs
            IFBHb497dj9rhkDHLdNcasJkmx6HiqhFK1WYHStemETZFLoULSqCWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T08:30:07Z"
    mac: ENC[AES256_GCM,data:tkLs2uMGm6Ux3PgDr6C2+mFRfmngwmeWLlI2MMcm2jfy3jmwJ5nBxAHD56busP1x3hbw5cHRfTrrBF2TjJi5JuShDUCMY2Zrm1540M+/IOYpeaZtO05VRzi/JfIMqayrZyz3qKhigP3pCckZ/WWMfRF/4OL8TGwCuxoRGMq4GKA=,iv:q2zCuF5ZAa+ziYP5cUdQEgLqACc+tlRjJUMOCGvEwGU=,tag:xTU+bhf/YsmyJxq2/cV60Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
