apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:FMufmAvQ10zQu0MqsY4/pk3ucycK0lkWG//RnIxU4oem0mIf,iv:RXOoa4s+rsawzRz7BBfKd7TzlGnXPghoK72aQChQN1o=,tag:HAXgnzL6m9kWLDJu7EqJww==,type:str]
    credentials.json: ENC[AES256_GCM,data:nSh8qFhdKm8RFloWEZMDnYUrUBokCVmPhEtmwkJXC+iX4RV+g6cUYteMDjuI5SsLz1l5b56jzb/nubTv8t7NQzjtzda3ny8OqaZ6PXfE+Oc7t3P9+zuQRNB08vEP14PAbIBOOhP7NYOf+EnqU04x81XqxRl8sXcLAlT9aaQD7cL7NAT7/krwKXaIA4SVqfmrgUHaT5HCZ6YPhBO4oYAKf0M0S4eLSr35H2xds+NTMw==,iv:YH3QuAeXqFCeFHvQXbWdvOuXXhS6XOA71fH7iKkDE5s=,tag:jrk8Ib7gpYf0QXJRaH8f6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2dFJlcmhBUExnN0thYXhL
            NnpLOUk4dGplenhHUDdhZ0c1WGkwd3MwVXdVCkt6ZzZWTW4ySjRHWlZLTGZFKzJa
            YU5tcERaQ1kydGhUUVFmRjQrK0ZPMkUKLS0tIHdiTnlmVlhjcm5kM0I5eU96ZWVk
            dFM3T3NVRG1iM1RWMzVmbXgzdlVlWWcK5LeT3WtLy86Evi1m8BcmKI/LPJ3mf2lU
            YKIya9pd1AdL8EHQ0nV9QfKZb0kydAQLWO4N233v72b3b0dS2C64GQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:14:38Z"
    mac: ENC[AES256_GCM,data:mKVrxDww5C1eMpM1zywld1HG1RtvFELEGb+L0lSQxQAUd+HHeT6Z1mP9n3uRbyrDtP+7z0kEvw2fgWlOsa8Wm3HpWx1kun8d8HTxTKJhF6IWRQNpknOMxPFtw2M2qLfxZMEJgaUi/g2N87YytTZeC2F30ysFxJGuqAl9csUnvzk=,iv:GIszkNz5zrkL5Uf2CS0tNCTjlqTW1S9uejgQhgi6V+s=,tag:9DOnGbT+lakPUg5RQ4Xj9w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
