# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:DGZIzaKgg9Bo5bZE30RPj4SRzj2i3D/wPGk4ijUn+rrQQQEWdf/0ww==,iv:TelkL0Z/Umlyhqry+kWLlszjcxh73LwyPy5JqB+c2D0=,tag:dC0a6ouTKv6mQKQMRqa9Tw==,type:str]
sops:
    age:
        - recipient: age1tcah38ehyckvyd20eg8x874sl58clvf9w6y60p3qqxykaatwq33s6sealk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWakpTdnpCcEJ4Z094V0pB
            MG0vWlhET1l0NjFGU0pTVm5XZisyY2FDWUNvCnlPbWkzUm0ydzhhSU95eGErYkhR
            WEFpeTlSaDNSZTZHUUViL21oZ1NCNE0KLS0tIHZQbWRXaXVITHJXa3JPdk5LNEtL
            ejBueGJPaFF2cWtCZ242VXphbWdZTEEKKOb4CnZleJBYhcZAEXZ9UlGczL0i7oIF
            qW6JCJwJVG7K7ueX06G7gN6p/Mr1RPuFEcsAJfvI/rQMLqaQBkk2sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-28T00:12:34Z"
    mac: ENC[AES256_GCM,data:6S/tXgphpgpYUyyGQGgpK1em9MLCUTqVvK8+AJkZfGKqkiyOdZxr0YI9AbOVNuv2X7xenEKHjwzauKgS3AQugAHhOJesEdyaigIP9D5B1E5Nt/UL9baqPjELq8i9z1btP8SQtrbOujUDhLljCrER7R1fb064/oNdLc8+nZ1tK0k=,iv:grAw7qVyaf0TbZlXvcEakAMRTeNsLBrWPyqf1euu1u8=,tag:Xx7FFtjVTiT7S5yfBWl3Xg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
