---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-workspace-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 200Gi
