# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
#  dependsOn:
#    - name: local-path-provisioner
#      namespace: storage
#    - name: volsync
#      namespace: volsync
  values:
#    defaultPodOptions:
#      affinity:
#        nodeAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#            nodeSelectorTerms:
#            - matchExpressions:
#              - key: node-role.kubernetes.io/worker
#                operator: In
#                values:
#                - worker
#          preferredDuringSchedulingIgnoredDuringExecution:
#          - weight: 50
#            preference:
#              matchExpressions:
#              - key: node-role.kubernetes.io/worker
#                operator: In
#                values:
#                - worker
    controllers:
      paperless:
        labels:
          nfsMount: "true"
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.17.1
            env:
              # Configure application
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              PAPERLESS_REDIS_PREFIX: pngx
              PAPERLESS_URL: https://paperless.${SECRET_DOMAIN}
              PAPERLESS_PORT: "8000"
              PAPERLESS_TIME_ZONE: Australia/Victoria
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              PAPERLESS_TIKA_ENABLED: 1
              PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
              # Configure Remote User auth
              PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
              PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "false"
              # Configure folders
              PAPERLESS_CONSUMPTION_DIR: /data/nas/consume
              PAPERLESS_DATA_DIR: /data/local/data
              PAPERLESS_EXPORT_DIR: /data/nas/export
              PAPERLESS_MEDIA_ROOT: /data/local/media
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGES: eng
              PAPERLESS_OCR_LANGUAGE: eng
              # Configure redis integration
              PAPERLESS_REDIS: redis://dragonfly.database.svc.cluster.local:6379
              # Configure user permissions
              USERMAP_GID: "65542"
            envFrom:
            - secretRef:
                name: paperless-secret
            resources:
              requests:
                cpu: 15m
              limits:
                memory: 2048Mi

          tika:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.1-minimal@sha256:20db3df89eaeb1b271dd840888fe909b88b12f4b86ef641ec07a1d45d4c5168f
            resources:
              limits:
                memory: 220Mi
              requests:
                cpu: 10m
                memory: 220Mi

          gotenburg:
            env:
              DISABLE_GOOGLE_CHROME: '1'
            image:
              repository: gotenberg/gotenberg
              tag: 8.21.1@sha256:91486863744f7420ca985ee6cef7c216910e40faffd378f3da7c0fad724d01ba
            resources:
              limits:
                memory: 30Mi
              requests:
                cpu: 10m
                memory: 30Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8000
    ingress:
      app:
        className: internal
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Paperless
          gethomepage.dev/icon: paperless.png
          gethomepage.dev/description: Document OCR Software
#          gethomepage.dev/widget.type: paperlessngx
#          gethomepage.dev/widget.url: http://paperless.media.svc.cluster.local:8000
#          gethomepage.dev/widget.key: "834c5259ed37fc041ba31a32f8d9bd608fb9a2ab"
        hosts:
        - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
          paths:
          - path: /
            service:
              identifier: app
              port: http
    persistence:
      config:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
          - path: /data/local
      nas:
        type: nfs
        server: 192.168.10.15
        path: /volume2/piNFS01/flux-cluster/media/paperless
        globalMounts:
          - path: /data/nas
