---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-config
  namespace: media
  labels:
    app.kubernetes.io/name: &name paperless
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 5Gi

  storageClassName: ceph-block
