---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationdestination_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: paperless-dest
  namespace: media
spec:
  trigger:
    manual: restore-once
  restic:
    repository: paperless-restic-secret
    copyMethod: Direct
    destinationPVC: paperless-config
    storageClassName: local-hostpath
