---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rsyslog-config-v1
  namespace: monitoring
  labels:
    app.kubernetes.io/name: &name rsyslog
    app.kubernetes.io/instance: *name
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ceph-block
