---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app pihole-exporter
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
    controllers:
      pihole-exporter:
        containers:
          main:
            image:
              repository: ghcr.io/osnabrugge/pihole-exporter
              tag: v1.0.1@sha256:c99456442c542d9d517afe2e863b92b2036548f0ee84c22c62f91a9e3396803c
            env:
              PIHOLE_HOSTNAME: 192.168.10.195
              PORT: 9617
            envFrom:
              - secretRef:
                  name: pihole-exporter-secret
            resources:
              requests:
                cpu: 15m
                memory: 30M
              limits:
                memory: 64M
    service:
      app:
        controller: *app
        ports:
          metrics:
            enabled: true
            protocol: TCP
            port: 9617
    serviceMonitor:
      app:
        serviceName: *app
        enabled: true
        endpoints:
        - port: metrics
          scheme: http
          path: /metrics
          interval: 5m
          scrapeTimeout: 1m
