# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stable-diffusion
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      main:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          runtimeClassName: nvidia
          terminationGracePeriodSeconds: 1
          securityContext:
            fsGroup: 1000

          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: nvidia.com/gpu.present
                        operator: In
                        values:
                          - "true"

          nodeSelector:
            nvidia.com/gpu.present: "true"

        containers:
          main:
            image:
              repository: ghcr.io/gabe565/stable-diffusion/webui
              tag: 1.10.1@sha256:39f178b1c5ad1bebacf4bde8f4348ce90666f40b303049a67dba64345dae1b43
              pullPolicy: IfNotPresent
            args:
              - --opt-sdp-attention
              - --upcast-sampling
              - --no-half
              - --no-half-vae
            env:
              IIB_ACCESS_CONTROL_ALLOWED_PATHS: /app/outputs
              TZ: ${TIMEZONE}
              NVIDIA_VISIBLE_DEVICES: all
              NVIDIA_DRIVER_CAPABILITIES: all

            resources:
              requests:
                cpu: 200m
                memory: 12Gi
                nvidia.com/gpu: 1
              limits:
                memory: 12Gi
                nvidia.com/gpu: 1

            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 90
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true

    service:
      main:
        controller: main
        ports:
          http:
            port: &httpPort 7860

    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/enable: "true"
          hajimari.io/appName: "Stable Diffusion"
          hajimari.io/icon: mdi:camera
          hajimari.io/group: "AI"
          hajimari.io/instance: "admin"
        hosts:
        - host: &host sd.${SECRET_DOMAIN}
          paths:
            - path: /
              service:
                identifier: main
                port: *httpPort

    persistence:
      data:
        enabled: true
        existingClaim: stable-diffusion-data-pvc
        globalMounts:
          - path: /data
          - path: /app/repositories

      outputs:
        enabled: true
        existingClaim: stable-diffusion-outputs-pvc
        globalMounts:
          - path: /app/outputs
