---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: ai
  name: stable-diffusion-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 64Gi
