---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui
  namespace: ai
spec:
  targetNamespace: ai
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/ai/open-webui/app
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: ollama
      namespace: ai
    - name: cloudnative-pg-cluster17
      namespace: database
#    - name: dragonfly-cluster
#      namespace: database
    - name: searxng
      namespace: selfhosted
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui-pipelines
  namespace: &namespace ai
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: open-webui-pipelines
  interval: 10m
  path: ./kubernetes/apps/ai/open-webui/pipelines
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: volsync
      namespace: volsync
  components:
    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: open-webui-pipelines-data
      VOLSYNC_CAPACITY: 1Gi
      VOLSYNC_CACHE_CAPACITY: 1Gi
