---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app cnpg-backup17
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      cnpg-backup:
        type: cronjob
        cronjob:
          schedule: "@daily"
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17@sha256:e0c87ce7df39d06b93f27cf2cc6a056611f13faaa88cc07ab4dc8bf7a85d0b11
            command: ["/scripts/list_dbs.sh"]
            env:
              EXCLUDE_DBS: app readarr_cache readarr_log postgres template0 template1
            envFrom: &envFrom
              - secretRef:
                  name: cnpg-backup17-secret
        containers:
          app:
            image:
              repository: docker.io/prodrigestivill/postgres-backup-local
              tag: 17@sha256:483fa15ecd998302bd312fc380cb1b3683a940881d9099d6dfe65bcc1e2714e8
            command: ["/bin/bash", "/backup.sh"]
            env:
              TZ: Australia/Melbourne
              POSTGRES_DB_FILE: /config/db_list
              POSTGRES_EXTRA_OPTS: "--blobs --clean --create --compress=9"
#              BACKUP_DIR: /backups
              BACKUP_KEEP_DAYS: "7"
              BACKUP_KEEP_WEEKS: "4"
              BACKUP_KEEP_MONTHS: "6"
              BACKUP_LATEST_TYPE: none
            envFrom: *envFrom
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        type: emptyDir
        globalMounts:
          - path: /config
      script:
        type: configMap
        name: cnpg-backup17-scripts
        defaultMode: 0775
        globalMounts:
          - path: /scripts/list_dbs.sh
            subPath: list_dbs.sh
            readOnly: true
#      nas:
#        type: nfs
#        server: 192.168.10.15
#        path: /volume2/piNFS01/flux-cluster/postgres/postgres17/backups
#        globalMounts:
#          - path: /backups
