---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app vaultwarden
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
    controllers:
      vaultwarden:
        type: statefulset
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.5.0
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: vaultwarden-secret
        containers:
          app:
            image:
              repository: vaultwarden/server
              tag: 1.34.1
            env:
              DATA_FOLDER: "data"
              ICON_CACHE_FOLDER: "data/icon_cache"
              ATTACHMENTS_FOLDER: "data/attachments"
              DOMAIN: "https://vaultwarden.${SECRET_DOMAIN}"
              TZ: "${TIMEZONE}"
              SIGNUPS_ALLOWED: "true"
              WEBSOCKET_ENABLED: "true"
              WEBSOCKET_ADDRESS: 0.0.0.0
              WEBSOCKET_PORT: 3012
#              SMTP_HOST: smtp-relay.home.svc.cluster.local.
              SMTP_HOST: "mail.internode.on.net"
#              SMTP_FROM: vaultwarden@${SECRET_DOMAIN}
              SMTP_FROM: "dstewen@internode.on.net"
              SMTP_FROM_NAME: vaultwarden
#              SMTP_PORT: 2525
              SMTP_PORT: 465
              SMTP_USERNAME: "dstewen"
              SMTP_PASSWORD: "1"
              SMTP_SECURITY: "force_tls"
              SMTP_DEBUG: true
            envFrom: *envFrom
            resources:
              requests:
                cpu: 100m
                memory: 64M
    service:
      app:
        controller: *app
        ports:
          http:
            port: &port 80
          websocket:
            enabled: true
            port: &websocket-port 3012
    ingress:
      app:
        enabled: true
        className: "internal"
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
          hajimari.io/icon: mdi:lock
          hajimari.io/enable: "true"
          hajimari.io/appName: "Vaultwarden"
          hajimari.io/group: "Home"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/group: Home
          gethomepage.dev/name: Vaultwarden
          gethomepage.dev/icon: si-vaultwarden
          gethomepage.dev/description: Vaultwarden

        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: *port
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  identifier: app
                  port: *port
              - path: /notifications/hub
                pathType: Prefix
                service:
                  identifier: app
                  port: *websocket-port
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: vaultwarden-data
