---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
#  - ./volsync_backblazeb2.yaml
#  - ./volsync_backblazeb2_openebs_local.yaml
#  - ./volsync_nas.yaml
#  - ./volsync_nas_openebs_local.yaml
  - ./volume.yaml
