---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app open-webui-pipelines
  namespace: &namespace ai
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: open-webui-pipelines
  interval: 30m
  path: ./kubernetes/apps/ai/open-webui-pipelines/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  dependsOn:
    - name: volsync
      namespace: volsync
#  components:
#    - ../../../../components/volsync
  postBuild:
    substitute:
      APP: *app
#      VOLSYNC_CLAIM: open-webui-pipelines-data
#      VOLSYNC_CAPACITY: 1Gi
#      VOLSYNC_CACHE_CAPACITY: 1Gi
  retryInterval: 1m
  timeout: 15m
