apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Llf+f4cmyvQ1jZP5WUMr0vvv6Std/UUVLrHahxPcvZEgh44b6FThLw==,iv:H2ic+G1NKIHwp6EXV2RKhDiij76Ge9O8Ga9ZEOCt0W4=,tag:qAGVXXPNes/wd/1fDmmISA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFTjhDc3ZIbFR2M0VmY3dV
            KzZ2WmJRN2JhMk9IdU5iZ2tmdG1zYU1CbFJzCmVDdWJwZU9qWHhBSFhpTnVzMUVs
            K1luRTlvS2c1YlBsZlk4cy9rbG5leDAKLS0tIGQ1YlRpc2cybk42VDJ3UE5Bbjcz
            eUExa05DQWlxYUx1SkF0SDBvbXhpckEKCfhHVS2xU9IO+DVqudVxe5rWJKwPo8Wp
            HKLdOVMTdtZWAdBpEsSv8UvVVZCj3coRb/7I+B6nVW+pUsFh968Ssw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:26:33Z"
    mac: ENC[AES256_GCM,data:G1+ZsVw6vX+MHifhdWI8HYLX4seXbAgmnF4ftzaPaJUh/QWQxKGlPVL4mg/MobFtCLd1KrWHwXFoDIc2qRLfCns8nWkzJF2GdjyyUehmpjzXCc1zCk1cVQU52mCxN4b9f1Ab9nz5fYUMUSUaYYgMZ4dOG6FIyzUC6bbpq3ys9Vw=,iv:qBi+5qz18jxdWCf+gbW7KpqsqQV4RzB7FznDP1GTmb8=,tag:O6Aj2OUnd7PjDN07usy7/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
