apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:Zg0ZCSIIWyzQFaSuE6a4gWlhjcmdI6j35NvdjKH5zFOfAkMW/PL7bA==,iv:HmXecF0WrN8fHX3hU4hScde2TExxVjubgb6cKK/cbIk=,tag:UN0AFVmS3gOrAdFu1CBnSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTW9sL09RUlhrSnV3NHJN
            QWV5TzlRbTlGTklzaTBBR3gyM2FyL2lWTW1vCnZkdmhoRUdjNFd1MEJaQmtYNVdu
            alJjK1U0dC9wYkpYWWVkMXJzSVZNbXMKLS0tIExUMUlPKzdXQjRxcUM2VzNEeXlp
            SEwwNTBCczgrSVFCUTNxOEZkMzVwNGMKg0Fs4swn+Oq1avi5MYQ4ijCM+OGxHA63
            0eglbV7OscM7rbbBEjymFIhGsTV0sex2fUR3FzvIB9b4JSx/wFltaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:58:23Z"
    mac: ENC[AES256_GCM,data:wGBqCjrC3YE4IugasRyXhgg8kEbY9RGcv0/mbaWnvcygkrN5S+bIzpMoQiQTFukViwmEAS/rDqKxDEbSIAeq/5JpBqG9Xo7jdsxmDapQDKp0jrR6wcX4fuZgu1i/Vi431mYz5VpkjiLhx1aEQBO50nzUF8Yb7Bm2vouyREtBKBo=,iv:dllVu9ToL1IHmFUOgBLmErIe6wbA+9zUETECmpAZpVc=,tag:FIj7hGbsIBxuztUnNShYsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
