apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:rWYplETNAuoWoHmrvBD+C17+Cc+VO3e9cLxHfLlufrH77TQaDnLTbw==,iv:6Io5TUKo95B79S4j2vl7cTIrZlGyCkpJH3gNGKqH17E=,tag:IE6AKWuqoo3Yl3jqft2Ppg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXby93aXA5NjFqMzZ0QXp0
            dlVabEh6QUZCY2l1NitXRHg2VTN1NEhnS0N3ClphTVdndjJCTzU0T0JlMC9tZlB2
            UUs2aHFPUDlwR0tuUU11Y0Rrdk1EV2MKLS0tIGtERUhkK203YkNLajVaNkdJVDlQ
            eEIvK01xcll6bVpjZGhQSlE1WU9UZkEKNwSTAfmfDDaRT9Pv2b0lRmEiC/jqoZRT
            UNavO+eKlwrTsk7LHudt3iS5oKVLMgqqmb2q4AAwd/MTrHwyUTSPrg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:14:38Z"
    mac: ENC[AES256_GCM,data:li7Odyh3nBvT68D46k4qTtdEyPiC1tUjopUIVDZS/njKrZenbhYtB+Or8eNAqPx0Cm7EH+LWbNYii5hbWPWC+iRWcytSgbsWucb0eNGJsAjG8DP8yoMEYSlpY1OVJCgG6NdWSzOKAw6wAePGLmUaej6Hlh2UHuLlRqFL0tp30CY=,iv:tT+bjyESgdRcYW/1KebNVwv9CERrK7brpS7axGlSk0k=,tag:P9L54gPeRKra9wXFBJ7J2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
