---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: trivy-operator
      version: 0.29.1
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    excludeNamespaces: "{{ .Release.Namespace }}"
    operator:
      replicas: 1
      scanJobsConcurrentLimit: 3
      scanJobTimeout: 15m
      scanJobTTL: 10s
      scanJobCompressLogs: false
      builtInTrivyServer: true
      metricsVulnIdEnabled: true
      vulnerabilityScannerScanOnlyCurrentRevisions: true
      configAuditScannerScanOnlyCurrentRevisions: true
    trivy:
      ignoreUnfixed: true
      mode: ClientServer
      storageClassName: openebs-hostpath

      slow: true
      # -- resources resource requests and limits for scan job containers
      resources:
        requests:
          cpu: 100m
          memory: 100M
      # Defaults to 500m CPU and 500M memory limit
        limits:
          cpu: 500m
          memory: 1000M

    serviceMonitor:
      enabled: true
      namespace: trivy-system
#    trivyOperator:
#      scanJobNodeSelector:
#        node-role.kubernetes.io/worker: worker
#    nodeSelector:
#      node-role.kubernetes.io/worker: worker
