---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich
  namespace: media
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: immich
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DB_DATABASE_NAME: &dbName immich
        DB_HOSTNAME: &dbHost postgres16-rw.database.svc.cluster.local
        DB_USERNAME: &dbUser "{{ .POSTGRES_SUPER_USER }}"
        DB_PASSWORD: &dbPass "{{ .POSTGRES_SUPER_PASS }}"
        JWT_SECRET: "{{ .JWT_SECRET }}"
        TYPESENSE_API_KEY: "{{ .TYPESENSE_API_KEY }}"
        HOMEPAGE_VAR_IMMICH_API_KEY: "{{ .IMMICH_API_KEY }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbName
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_USER_SUPERUSER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: immich
    - extract:
        key: cloudnative-pg
