---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-upload-pv
spec:
  storageClassName: immich-upload-storage-class
  capacity:
    storage: 1Mi # Size does not matter
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 192.168.10.15
    path: /volume2/piNFS01/flux-cluster/media
  # Note: The first two options are strictly for NFSv4.2
#  mountOptions: ["nfsvers=4.2", "nconnect=8", "hard", "noatime"]
  mountOptions: ["nfsvers=4.1", "hard", "noatime"]
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-upload-pvc
  namespace: media
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: immich-upload-storage-class
  resources:
    requests:
      storage: 1Mi # Size does not matter
