---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app system-upgrade-controller
spec:
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  interval: 30m
  maxHistory: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      system-upgrade-controller:
        strategy: RollingUpdate
        replicas: 1
        containers:
          app:
            image:
              repository: docker.io/rancher/system-upgrade-controller
              tag: v0.16.2@sha256:ae933d9d81e9c42e316989a0ce7b1fb0dfe93afe5469631b8f384141b89b106a
            env:
              TZ: Australia/Melbourne
              SYSTEM_UPGRADE_CONTROLLER_LEADER_ELECT: true
              SYSTEM_UPGRADE_CONTROLLER_NAME: *app
              SYSTEM_UPGRADE_CONTROLLER_NAMESPACE:
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              SYSTEM_UPGRADE_CONTROLLER_NODE_NAME:
                valueFrom:
                  fieldRef:
                    fieldPath: spec.nodeName
              SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: "99"
              SYSTEM_UPGRADE_JOB_PRIVILEGED: false
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
    rawResources:
      talosServiceAccount:
        apiVersion: talos.dev/v1alpha1
        kind: ServiceAccount
        spec:
          spec:
            roles:
              - os:admin

    rbac:
      bindings:
        system-upgrade-controller:
          type: ClusterRoleBinding
          roleRef:
            kind: ClusterRole
            name: cluster-admin
          subjects:
            - identifier: system-upgrade-controller

    serviceAccount:
      system-upgrade-controller: {}
