---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: atuin-secret
    template:
      engineVersion: v2
      data:
        ATUIN_DB_URI: |-
          postgres://{{ .ATUIN_POSTGRES_USER }}:{{ .ATUIN_POSTGRES_PASSWORD }}@{{ .ATUIN_POSTGRES_HOST }}/atuin
        ATUIN_POSTGRES_USER: &dbUser "{{ .ATUIN_POSTGRES_USER }}"
        ATUIN_POSTGRES_PASSWORD: &dbPass "{{ .ATUIN_POSTGRES_PASSWORD }}"
        ATUIN_POSTGRES_HOST: &dbHost "{{ .ATUIN_POSTGRES_HOST }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: atuin
        INIT_POSTGRES_HOST: *dbHost
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: atuin
    - extract:
        key: cloudnative-pg
