---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app atuin
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  values:
    controllers:
      atuin:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 17.6.0
            envFrom: &envFrom
              - secretRef:
                  name: atuin-secret
        containers:
          app:
            image:
              repository: ghcr.io/atuinsh/atuin
              tag: v18.9.0@sha256:86ab9638b278486ccb4e75645272f332b4d5ff590bacb3ae1c4194c0d7233424
            env:
              ATUIN_HOST: 0.0.0.0
              ATUIN_PORT: &port 80
              ATUIN_OPEN_REGISTRATION: "true"
              ATUIN_METRICS__ENABLE: "true"
              ATUIN_METRICS__HOST: 0.0.0.0
              ATUIN_METRICS__PORT: &metricsPort 8080
              ATUIN_TLS__ENABLE: "false"
            envFrom:
              - secretRef:
                  name: atuin-secret
              - secretRef:
                  name: cluster-secrets
            args: ["server", "start"]
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: atuin
        ports:
          http:
            primary: true
            port: *port
          metrics:
            port: *metricsPort
    serviceMonitor:
      app:
        serviceName: atuin
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s

    route:
      app:
        hostnames: ["sh.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      config:
        type: emptyDir
