---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: boinc-arm64
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: boinc-arm64-secret
    template:
      engineVersion: v2
      data:
        BOINC_GUI_RPC_PASSWORD: "{{ .BOINC_GUI_RPC_PASSWORD }}"
  dataFrom:
    - extract:
        key: boinc-arm64
