---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: boinc-arm64
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      boinc-arm64:
        pod:
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                - matchExpressions:
                  - key: node-role.kubernetes.io/worker
                    operator: In
                    values:
                    - worker
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: boinc/client
              tag: arm64v8
            env:
              TZ: "${TIMEZONE}"
              BOINC_GUI_RPC_PASSWORD: "123"
              BOINC_CMD_LINE_OPTIONS: "--allow_remote_gui_rpc"
#            envFrom:
#              - secretRef:
#                  name: boinc-secret
            resources:
              requests:
                cpu: 10m
              limits:
                cpu: 2000m
                memory: 1Gi

    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile: { type: RuntimeDefault }
#      annotations:
#        k8s.v1.cni.cncf.io/networks: |
#          [{
#            "name":"multus-iot",
#            "namespace": "kube-system",
#            "ips": ["172.16.20.99/24"]
#          }]
    service:
      app:
        controller: boinc-arm64
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: ${SVC_BOINC_ADDR_ARM64}
        ports:
          http:
            port: 80
          https:
            port: 443
          manager:
            port: 31416

    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: internal.davidstewen.com
        className: internal
        hosts:
          - host: boinc-arm64.davidstewen.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: boinc-arm64-config
        globalMounts:
          - path: /var/lib/boinc
            readOnly: false
