---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: boinc-arm64-config
  namespace: ai
  labels:
    app.kubernetes.io/name: &name boinc-arm64
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath
  resources:
    requests:
      storage: 1Gi
