---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - config-map.yaml
  - helmrelease.yaml
#configMapGenerator:
#  - name: apc-ups-dashboard
#    files:
#      - apc-ups-dashboard.json=./dashboard.json
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
#  labels:
#    grafana_dashboard: "true"
