---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres17
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5-5
  primaryUpdateStrategy: unsupervised
  storage:
    size: 20Gi
    storageClass: openebs-hostpath
  superuserSecret:
    name: cloudnative-pg-secret
  enableSuperuserAccess: true
# Note: Bootstrap is needed when recovering from an existing cnpg cluster
  bootstrap:
    recovery:
      source: &previousCluster postgres17-v1
#    initdb:
#      import:
#        type: monolith
#        databases: ["*"]
#        roles: ["*"]
#        source:
#          externalCluster: cnpg16
  postgresql:
    parameters:
      max_connections: "600"
      max_slot_wal_keep_size: 10GB
      shared_buffers: 512MB
  resources:
    requests:
      memory: "1Gi"
      cpu: "500m"
    limits:
      memory: "2Gi"
  monitoring:
    enablePodMonitor: true
  backup:
    retentionPolicy: 30d
    barmanObjectStore:
      wal:
        compression: bzip2
        maxParallel: 8
      data:
        compression: bzip2
      destinationPath: s3://cnpg-backups-new/
      endpointURL: http://192.168.10.198:9000
      serverName: &currentCluster postgres17-v2
      s3Credentials:
        accessKeyId:
          name: cloudnative-pg-secret
          key: aws-access-key-id
        secretAccessKey:
          name: cloudnative-pg-secret
          key: aws-secret-access-key
# Note: externalClusters is needed when recovering from an existing cnpg cluster
  externalClusters:
    - name: *previousCluster
      barmanObjectStore:
        wal:
          compression: bzip2
          maxParallel: 8
        destinationPath: s3://cnpg-backups-new/
        endpointURL: http://192.168.10.198:9000
        s3Credentials:
          accessKeyId:
            name: cloudnative-pg-secret
            key: aws-access-key-id
          secretAccessKey:
            name: cloudnative-pg-secret
            key: aws-secret-access-key
#    - name: cnpg16
#      connectionParameters:
#        host: postgres16-rw.database.svc.cluster.local
#        user: postgres
#        dbname: postgres
#      password:
#        name: cloudnative-pg-secret
#        key: password
#  affinity:
#    nodeAffinity:
#      requiredDuringSchedulingIgnoredDuringExecution:
#        nodeSelectorTerms:
#        - matchExpressions:
#          - key: kubernetes.io/arch
#            operator: In
#            values:
#            - arm64
#      preferredDuringSchedulingIgnoredDuringExecution:
#      - weight: 50
#        preference:
#          matchExpressions:
#          - key: node-role.kubernetes.io/worker
#            operator: In
#            values:
#            - worker
