---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter-s3400-48t6sp
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - worker
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    fullnameOverride: *app
    resources:
      limits:
        memory: 64Mi
      requests:
        memory: 32Mi
    serviceMonitor:
      enabled: true
      params:
        - name: s340048t6sp
          auth: [public_v2]
          module: [if_mib]
          target: 192.168.10.3
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
