---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: wyoming-services
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  maxHistory: 3

  install:
    createNamespace: true
    remediation:
      retries: 3

  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  uninstall:
    keepHistory: false

  values:
    defaultPodOptions:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - arm64
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 50
            preference:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: In
                values:
                - worker
    controllers:
      piper:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: ceph-block
              globalMounts:
                - path: /data

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: rhasspy/wyoming-piper
              tag: 1.5.4
            args:
              - --voice=en-gb-southern_english_female-low

            resources:
              requests:
                cpu: 500m
                memory: 250Mi
              limits:
                memory: 500Mi

      whisper:
        type: statefulset

        statefulset:
          volumeClaimTemplates:
            - name: data
              accessMode: ReadWriteOnce
              size: 5Gi
              storageClass: ceph-block
              globalMounts:
                - path: /data

        annotations:
          reloader.stakater.com/auto: "true"

        containers:
          main:
            image:
              repository: rhasspy/wyoming-whisper
              tag: 2.5.0
            args:
              - --model=small
              - --language=en

            resources:
              requests:
                cpu: 500m
                memory: 250Mi
              limits:
                memory: 2500Mi

      openwakeword:
        type: statefulset

        annotations:
          reloader.stakater.com/auto: 'true'

        containers:
          main:
            image:
              repository: rhasspy/wyoming-openwakeword
              tag: 1.10.0
            args:
              - --preload-model
              - 'ok_nabu'
              - --custom-model-dir
              - /custom

            resources:
              requests:
                cpu: 100m
                memory: 32Mi
              limits:
                memory: 128Mi

    service:
      piper:
        type: LoadBalancer
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_WYOMING_PIPER_ADDR}
        controller: piper
        ports:
          http:
            port: 10200

      whisper:
        type: LoadBalancer
        controller: whisper
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_WYOMING_WHISPER_ADDR}
        ports:
          http:
            port: 10300
            protocol: TCP

      openwakeword:
        type: LoadBalancer
        controller: openwakeword
        annotations:
          io.cilium/lb-ipam-ips: ${SVC_WYOMING_WAKEWORD_ADDR}
        ports:
          http:
            port: 10400

    persistence:
      openwakeword-config:
        enabled: true
        type: configMap
        name: openwakeword-config
        advancedMounts:
          openwakeword:
            main:
              - path: /custom
                readOnly: true
