---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app wallos
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
#    - name: local-path-provisioner
#      namespace: storage
    - name: rook-ceph-cluster
      namespace: rook-ceph
#    - name: volsync
#      namespace: volsync
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          wallos:
            image:
              repository: ghcr.io/ellite/wallos
              tag: 4.1.1
            env:
              TZ: ${TIMEZONE:=Etc/UTC}
              SERVER_PORT: 80
              SERVER_ROOT: /data/git/haraldkoch.git
            # probes:
            #   liveness:
            #     enabled: true
            #   readiness:
            #     enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 60Mi
              limits:
                memory: 120Mi
            securityContext:
              allowPrivilegeEscalation: false
              # this program writes _everywhere_
              readOnlyRootFilesystem: false
              # ERROR: [pool www] failed to setgid(82): Operation not permitted (1)
              #capabilities: { drop: ["ALL"] }
    # Listens on port 80, chown's around
    defaultPodOptions:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
        fsGroupChangePolicy: "OnRootMismatch"
        runAsNonRoot: false
        seccompProfile:
          type: RuntimeDefault
    service:
      app:
#        controller: main
        ports:
          http:
            port: &port 80
#    ingress:
#      main:
#        className: internal
#        hosts:
#          - host: "{{ .Release.Name }}.${CLUSTER_DOMAIN}"
#            paths:
#              - path: /
#                service:
#                  identifier: main
    route:
      app:
        hostnames: ["wallos.davidstewen.com"]
        parentRefs:
          - name: internal
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - name: *app
                port: *port

    persistence:
      data:
        existingClaim: ${VOLSYNC_CLAIM}
        globalMounts:
          - path: /var/www/html/db
            subPath: db
          - path: /var/www/html/images/uploads/logos
            subPath: logos
