---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-uhd
  namespace: media
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 15Gi
  storageClassName: ceph-block
