---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pipelines-scripts
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
