---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - ./volsync_nas.yaml
#  - ./volsync_nas_openebs_local.yaml
#  - ./volsync_backblazeb2.yaml
#  - ./volsync_backblazeb2_openebs_local.yaml
#  - ./config-pvc.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
#  - ../../../../templates/volsync
configMapGenerator:
  - name: node-red-configmap
    files:
      - ./resources/settings.js
generatorOptions:
  disableNameSuffixHash: true
#  annotations:
#    kustomize.toolkit.fluxcd.io/substitute: disabled
