---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syslog
  namespace: monitoring
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      syslog:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/syslog-ng
              tag: 4.8.3
              pullPolicy: IfNotPresent
            envFrom:
            - configMapRef:
                name: syslog-configmap
            securityContext:
              runAsUser: 0
              runAsGroup: 0
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            resources:
              requests:
                memory: 50M
              limits:
                memory: 100M
        pod:
          tolerations:
            - key: "master"
              operator: "Equal"
              value: "false"
              effect: "NoSchedule"

    service:
      app:
        controller: syslog
        type: LoadBalancer
#        externalTrafficPolicy: Cluster
        annotations:
          lbipam.cilium.io/ips: 10.200.15.226
        ports:
          syslog-udp:
            enabled: true
            port: 514
            protocol: UDP
          syslog-tcp:
            enabled: true
            port: 1514
            protocol: TCP
    persistence:
      config:
        enabled: true
        existingClaim: syslog-config-v1
        globalMounts:
          - path: "/config"
