---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
#  - ./arc-controller-scrape.yaml
#  - ./arc-listener-scrape.yaml
#  - ./rook-ceph-scrape.yaml
  - ./minecraft-prometheus-exporter-scrape.yaml
  - ./opnsense.yaml
#  - ./proxmox-node-exporter-scrape.yaml
