---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/scrapeconfig_v1alpha1.json
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: opensense-node-exporter
spec:
  staticConfigs:
    - targets:
        - "192.168.10.1:9100"
  metricsPath: /metrics
