apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:d4jIxdx06nLwqSOmwrh7,iv:oGB81Y59RjEDQnJOD+AbJlX5uHInI0qLFScgwoJI/KU=,tag:lJH2QXGBrbUCgsRYYYY0zg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:h9wmrnQUX1sKwW09oxMlkkY4usnA,iv:ukmBVEGlKVZ3J8c3L50wkxLth6XxtHrbInJsUYiPwtY=,tag:CGTvFSKe9hmsvVa4vrZxig==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pwqvTzq3/GuZr/3Xmu25Me20N71l/V48Gja6cX5b38GOzBAW,iv:u/UrA+fqI95uIvema6oP+uWWPtUBfHSx65rISWALoEw=,tag:zWzkUc3lK+hOIO4B7Hiy9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTDZ2Nkpvam80dFhPNHdN
            eHNxQ0NmZDFBM2RkQW1vem94WU5oVjIzVEVFCmo2cGZELzBINjdtaFY1NC9ydUF0
            dFo3bG12NGFrZjRnM3p5UlNFUGdLeUkKLS0tIHd4WENvbG5GNTg4UmVwaWszdWc2
            M3JoRVhUdzUyOFZWMzdwaEx3dGhVYjAKS3tksWX0TVMFBH4hsCyNT/FSaYEVJLpX
            jpKKr3xrz3yQbORHBmoFqhqzz97zNwMZk1I2tbFp5LQrPmsoPTkD7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T10:08:55Z"
    mac: ENC[AES256_GCM,data:S+jcFYTmQ+jA73HSdYv1xbDLnCC6EA8qBoghkEnKQWP8sgaOQX4r5t8r8cugDngQr7p8yq0cg2oazCbAJiE3uLjukwNYeZ5xgNWfeJUbuI3XUXEd7g8FL53cUn8HW+iiXBJVpX/7CPZpqMIBN8spXRc9/DMxo+AKI77s6myBAtw=,iv:P6QKBrjbCxOKhiUjq5hxCzF66VIMrAB8i5Be3HnSYGo=,tag:SJoPmhwevRUQoVwGbjmoxg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
