apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D6WcYaxyajfYsAX3t/cn,iv:ca3Vj5uWyz/G7JchpKPQhUMBxlyRPdIJSOrWTD9zwfA=,tag:FTUQs3pTbhsHoGqM8ZMG1w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8e5k5+dGR0C1kD/lTa8BLqxcUUfx,iv:nW73qU5gIthhruPe4MpV6WsAu5y7gxV3ZJpLRCfSwOA=,tag:ZCatwrLkO23IodmOZvC+JQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pave0DUffUF8CQ12rMM2p9qnpx+ftjxDeG8w9JKgbL/9JdoS,iv:Zy/e3L6xK4S7vP+6kkU9DR0Npr6FMgppCyt8L+YeS4c=,tag:mTN/8ob1ZrE2aL9uE0yodg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VHIxVzhoMUlCOTFHY013
            V0dYSlRrVjZPZFU2ekN0Z2I3bFlGa2sxU25nCis2ZzNqYlJnaS9vV3NzUDg2ZkNC
            OG5DcldKYzREcHdDVk9GeVRXZUF2dncKLS0tIFFwZXk3ZTNQK3hSbjFLVE5IaHlI
            bUlhQ0tEdEVzL25TMVlkWTQyRGlGWGsKzackCmn3GlIns1z6n4F9eFwda2FYFeXf
            9JUQgerZO5ycwH5o8H2btZuU9dTYpw5lMrI8uz3j2mA+5fHengY0YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:58:23Z"
    mac: ENC[AES256_GCM,data:eaAer66vx5lWLG9sxsE6pvVWqfBVATWZuzVlN8chUa45k2d7xcm+RcdKF/rcLUtZsDzUr/l5w+0s7BniYMrpDtH9przX/RxjnTJmOeabpXW8DOKudwgLtSKITW5YWPleoqoIVVKs7E2bKnqLzycJXvda78/Z/WJeAbIqCtk47nI=,iv:NXakLrgg6szHUwYYzgszVVQRdgkTEbkmEQv0StV9FGg=,tag:VAVzcm66yrv5xaDzvVDKrg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
