apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:D6WcYaxyajfYsAX3t/cn,iv:ca3Vj5uWyz/G7JchpKPQhUMBxlyRPdIJSOrWTD9zwfA=,tag:FTUQs3pTbhsHoGqM8ZMG1w==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:8e5k5+dGR0C1kD/lTa8BLqxcUUfx,iv:nW73qU5gIthhruPe4MpV6WsAu5y7gxV3ZJpLRCfSwOA=,tag:ZCatwrLkO23IodmOZvC+JQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:pave0DUffUF8CQ12rMM2p9qnpx+ftjxDeG8w9JKgbL/9JdoS,iv:Zy/e3L6xK4S7vP+6kkU9DR0Npr6FMgppCyt8L+YeS4c=,tag:mTN/8ob1ZrE2aL9uE0yodg==,type:str]
    SVC_MC_ADDR: ENC[AES256_GCM,data:sUZNIsj5AhTK/9jSQI8=,iv:dlzrcmHNbMfD6dAOpkS95zVqKcnNSz7MBPBqbBDNezM=,tag:1bQ80quIjAUc4LzCYQVZqA==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:5d28+3r/K5PjrWno9dE=,iv:VBPWdlSnDR2Q1V1c+mSs5e40lfWi+fOdspDEwhpRxcY=,tag:hDx4okR+SNg0DBBQHsPXjQ==,type:str]
    PI3B_IP: ENC[AES256_GCM,data:eOEXfepRggDLuLOwmw==,iv:y3JuirTlsUY7eqFr1qt5Djy1hsMvWLEZYAazQYy1aV4=,tag:Zo/6MXImKqDBXvWkgyOl5A==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:Z44cNq2HZuKTIXBXxeM=,iv:tSLT9O0LNpcvQ9SWalgpMJaOuyhd6jFhQiFi/OKaizs=,tag:F84U9T0dUNtWi7ohYSn4ag==,type:str]
    SVC_POSTGRES_ADDR: ENC[AES256_GCM,data:/MMjcyQTDV9mN3hWzWg=,iv:1zQwbuNVglaurpnkJX5MdJu576c9mCSjB1jkIogk78U=,tag:IWSU7IP69sWyGQmBj6/F7w==,type:str]
    SVC_QBITTORENT_ADDR: ENC[AES256_GCM,data:KJgwVvTpPkgTHi8FsV0=,iv:Cpk0o8TKWTOG+nawTuzs836gm7Kb0C+lNsSKb16orok=,tag:ajM+MDlzEYh025NROuyy0w==,type:str]
    SVC_LOCALAI_ADDR: ENC[AES256_GCM,data:DrhyK8IMyKxU3diJa34=,iv:4Wd5hxgWv+GPRVPTWFloWW2h7zvK8jn8OTdOJK3sE3o=,tag:c1TEJ5/kW5SfYESzMpTfeg==,type:str]
    SVC_SMTP_ADDR: ENC[AES256_GCM,data:lR/27WdI5CvSK00Y/TU=,iv:PgAtwuzmcNcG+HX9xXnjtJkJLS4DTxtrz1Yt0N3xUYU=,tag:WH1RIz7/kjPi339pN8fb+g==,type:str]
    SVC_UNIFI_ADDR: ENC[AES256_GCM,data:9rHfIB1nBqhx/3ascJ8=,iv:l9rDB4s3XFdFAmpKofAeBJRfYeXQjHCDj23+PFSf8/w=,tag:oSkmIBA6BlR4Irp+oWKn3w==,type:str]
    NAS_IP: ENC[AES256_GCM,data:r560eouBQZ6b5HdoVg==,iv:aRp0gqs6JC5gUNKn6NjvrdM7qqO0dPRkEtdFFFKWBks=,tag:eGjbsqIgW/lDQhFqkMx2PA==,type:str]
    HASS_PI4: ENC[AES256_GCM,data:5SPJnJd0O7w5URs1FQ==,iv:39s5IwGeJ1WW9S4AqsSWpboD3VBBGWmOx1nm17nDRwE=,tag:rPSrNA7h06HxLkqHkAZLlg==,type:str]
    HASS_YELLOW: ENC[AES256_GCM,data:xMlP/aBwovp98eNiZQ==,iv:rgjPJVV/wlRPorEggS5F80JbxgxkVJschatQ+scxaWU=,tag:6/+93TnMmW9d3NS4fC5Chw==,type:str]
    PIHOLE_IP: ENC[AES256_GCM,data:CCsQShz7ZFDWcFZJ1uU=,iv:H6xvXJH0bs3O9AjhVWC/VDGvp2DQAk8zMLWGnBl9RyY=,tag:ms4+T8g4zIbucWRC1dTgrQ==,type:str]
    SYN_MINIO: ENC[AES256_GCM,data:7/QjJ7pdvElkfIcLY3g=,iv:w2KIM4nuFt9tyvQaqukE35iQHuCAL7vE8v0bfv//Q88=,tag:rd32qWHOoxSpYihNVzKznQ==,type:str]
    NFS_SERVER_CAMERAS_DIR: ENC[AES256_GCM,data:8q7BVIvZGh4CFi6ghNW5CTigElBYMAb9tln81F0lh5nTPby2VZfaAHW8Iw==,iv:+jN6M0fsnpVVAFWYe4LpKiCTQLb0F15u5s1vdtqm+qU=,tag:ix8CfyGVntUs0rhqENNRbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VHIxVzhoMUlCOTFHY013
            V0dYSlRrVjZPZFU2ekN0Z2I3bFlGa2sxU25nCis2ZzNqYlJnaS9vV3NzUDg2ZkNC
            OG5DcldKYzREcHdDVk9GeVRXZUF2dncKLS0tIFFwZXk3ZTNQK3hSbjFLVE5IaHlI
            bUlhQ0tEdEVzL25TMVlkWTQyRGlGWGsKzackCmn3GlIns1z6n4F9eFwda2FYFeXf
            9JUQgerZO5ycwH5o8H2btZuU9dTYpw5lMrI8uz3j2mA+5fHengY0YQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T04:36:44Z"
    mac: ENC[AES256_GCM,data:UKvPCAlEl6gU5iqB95owS27LJxQoQxrv7k08SvAdW7Nj4JdNwK0A7Mf4605OF8xv55exWzFMLW5e6569T4vKc/XIWr1tmPv/6yffzkeQ3tK7ShNXxlZyVd4iKOeMXjPTf0fwoXmpOk3Wc3SQmOAwryUai0olYhVFBJQPAejSzYM=,iv:agOsM9LZnmjgMOw8eqh994YJU1/f1dIi4tw6Whdvaac=,tag:d9E4hcrlCrVvBtFtNksqFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
