---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: firefly-iii
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: firefly-iii-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DATABASE_URL: postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres17-rw.database.svc.cluster.local.:5432/firefly-iii
        APP_ENV: "{{ .APP_ENV }}"
        SITE_OWNER: "{{ .SITE_OWNER }}"
        LOG_CHANNEL: "{{ .LOG_CHANNEL	}}"
        APP_LOG_LEVEL: "{{ .APP_LOG_LEVEL }}"
        SEND_ERROR_MESSAGE: "{{ .SEND_ERROR_MESSAGE }}"
        STATIC_CRON_TOKEN: "{{ .STATIC_CRON_TOKEN }}"
        APP_URL: "{{ .APP_URL }}"
        TRUSTED_PROXIES: "{{ .TRUSTED_PROXIES }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: firefly-iii
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: firefly-iii
