---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app firefly-iii
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    controllers:
      firefly-iii:
        containers:
          app:
            image:
              repository: fireflyiii/core
              tag: version-6.1.15
            resources:
              requests:
                cpu: 15m
                memory: 128Mi
              limits:
                memory: 1000Mi
            probes:
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
              liveness:
                enabled: true
              readiness:
                enabled: true
            envFrom:
              - secretRef:
                  name: firefly-iii-secret
            env:
              TZ: "${TIMEZONE}"
              DB_CONNECTION: pgsql
              DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: host
              DB_PORT:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: port
              DB_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: dbname
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: user
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: password
          cronjob:
            image:
              repository: alpine
              tag: 3.22.0
              pullPolicy: IfNotPresent
            command:
              - sh
            args:
              - -c
              - >-
                echo "0 */3 * * * wget -qO- http://firefly-iii:8080/api/v1/cron/$(STATIC_CRON_TOKEN)"
                | crontab -
                && crond -f -L /dev/stdout
            env:
              - name: STATIC_CRON_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: firefly-iii-secret
                    key: STATIC_CRON_TOKEN
        initContainers:
          wait-database:
            image:
              repository: alpine
              tag: 3.22.0
              pullPolicy: IfNotPresent
            command:
              - sh
            args:
              - -c
              - >-
                until nc -w 1 -v $POSTGRES_HOST:5432;
                do echo "Waiting for database";
                done
            env:
              - name: POSTGRES_HOST
                valueFrom:
                  secretKeyRef:
                    name: pgo-cluster-pguser-fireflyiii
                    key: host
    service:
      app:
        controller: *app
        ports:
          http:
            port: 8080
    ingress:
      app:
        enabled: true
        className: internal
        hosts:
          - host: &host money.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      data:
        enabled: true
        existingClaim: firefly-iii-data
        advancedMounts:
          firefly-iii:
            app:
              - path: /var/www/html/storage/upload
