#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: plex-config-0
#  labels:
#    app.kubernetes.io/name: &name plex
#    app.kubernetes.io/instance: *name
#    snapshot.home.arpa/enabled: "true"
#spec:
#  accessModes:
#    - ReadWriteOnce
#
#  resources:
#    requests:
#      storage: 5Gi
#
#  storageClassName: openebs-hostpath
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-cache
  labels:
    app.kubernetes.io/name: &name plex
    app.kubernetes.io/instance: *name
    snapshot.home.arpa/enabled: "true"
spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 100Gi # Don't go below 60G. Check fs size on pvc before changing

  storageClassName: ceph-block
