---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./1password-charts.yaml
  - ./authentik.yaml
  - ./backube.yaml
  - ./bjw-s.yaml
  - ./cloudnative-pg.yaml
  - ./external-dns.yaml
  - ./external-secrets.yaml
  - ./grafana.yaml
  - ./prometheus-community.yaml
  - ./openebs.yaml
  - ./piraeus.yaml
  - ./rook-ceph.yaml
