---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app immich-microservices
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3

  dependsOn:
    - name: immich-server
      namespace: media

  values:
    controllers:
      main:
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
          configmap.reloader.stakater.com/reload: &configMap immich-configmap
          secret.reloader.stakater.com/reload: &secret immich

        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.142.0@sha256:29f12a20fd1975c9df06d99a65658cec40bf2357fb597499c32ee50a75f250ea
#            args: start-microservices.sh

            envFrom:
              - secretRef:
                  name: *secret
              - configMapRef:
                  name: *configMap

            resources:
              requests:
                gpu.intel.com/i915: 1
                cpu: 100m
                memory: 6000Mi
              limits:
                gpu.intel.com/i915: 1

        pod:
          enableServiceLinks: false

          nodeSelector:
            intel.feature.node.kubernetes.io/gpu: "true"

          topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: *app

    persistence:
      library:
        existingClaim: immich-upload-pvc
        globalMounts:
          - path: /usr/src/app/upload

      geocoding-dump:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.reverse-geocoding-dump

      geoname-dump:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/node_modules/local-reverse-geocoder/geonames_dump

      transformers-cache:
        type: emptyDir
        globalMounts:
          - path: /usr/src/app/.transformers_cache
