---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: snmp-exporter
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 9.6.2
  url: oci://ghcr.io/prometheus-community/charts/prometheus-snmp-exporter
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app snmp-exporter
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: snmp-exporter
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/worker
              operator: In
              values:
              - worker
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 50
          preference:
            matchExpressions:
            - key: kubernetes.io/arch
              operator: In
              values:
              - arm64
    fullnameOverride: *app
    resources:
      limits:
        memory: 64Mi
      requests:
        memory: 32Mi
    serviceMonitor:
      enabled: true
      params:
        - name: s340048t6sp
          auth: [public_v2]
          module: [if_mib]
          target: 192.168.10.3
        - name: upstairsap
          auth: [public_v2]
          module: [if_mib]
          target: 192.168.10.128
      relabelings:
        - sourceLabels: [__param_target]
          targetLabel: instance
