---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr-node
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       preference:
      #         matchExpressions:
      #         # Intel N100
      #         - key: feature.node.kubernetes.io/cpu-model.id
      #           operator: In
      #           values:
      #           - "190"
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         # Intel N100
      #         - key: feature.node.kubernetes.io/cpu-model.id
      #           operator: In
      #           values:
      #           - "190"
      #         - key: intel.feature.node.kubernetes.io/gpu
      #           operator: In
      #           values:
      #           - "true"
      # securityContext:
      #   fsGroup: 1000
      #   fsGroupChangePolicy: OnRootMismatch
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 44 # video
          - 125 # render
          - 105 # render
          - 568
    controllers:
      tdarr-node:
        containers:
          node:
            image:
              repository: haveagitgat/tdarr_node
              tag: 2.45.01@sha256:7e98e8b97350101bda7af1673e473edd65915f10a0c5ae040487dec220a870c8
            env:
            - name: nodeID
              value: kube-node
            - name: serverIP
              value: tdarr-server.media.svc.cluster.local.
            - name: serverPort
              value: 8266
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
              limits:
                cpu: 2
                gpu.intel.com/i915: 1
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      movies:
        type: nfs
        server: ${NAS_IP:=temp}
        path: /volume2/piNFS01/flux-cluster/media_new/media/Movies
        globalMounts:
          - path: /mnt/movies

      tv:
        type: nfs
        server: ${NAS_IP:=temp}
        path: "/volume2/piNFS01/flux-cluster/media_new/media/TV Shows"
        globalMounts:
          - path: /mnt/tv

      other-videos:
        type: nfs
        server: ${NAS_IP:=temp}
        path: "/volume2/piNFS01/flux-cluster/media_new/media/Other Videos"
        globalMounts:
          - path: /mnt/other-videos
