---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app n8n
  namespace: &namespace selfhosted
spec:
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  path: "./kubernetes/apps/selfhosted/n8n/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      APP_UID: "1000"
      APP_GID: "1000"
      VOLSYNC_CLAIM: n8n
      VOLSYNC_CAPACITY: 5Gi
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
