---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: synology-csi
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: synology-csi
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: dcardellino-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  values:
    connections:
      - host: ${SYNOLOGY_CSI_HOST}
        port: 5000
        https: true
        username: ${SYNOLOGY_CSI_USER}
        password: ${SYNOLOGY_CSI_PASSWORD}
    storageClasses:
      delete:
        isDefault: false
        reclaimPolicy: Delete
        volumeBindingMode: Immediate
        parameters:
          dsm: ${SYNOLOGY_CSI_HOST}
          fsType: ext4
          location: /volume2
          type: thin
      retain:
        isDefault: false
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
        parameters:
          dsm: ${SYNOLOGY_CSI_HOST}
          fsType: ext4
          location: /volume2
          type: thin
