apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:cZ9ZYp1RCVdW32thaS6zwdOaXvS3AS3gGgOvDrcI0ME=,iv:4NRDJNHckUUHBWDinjjRYIIe+M51O0i2k4tBpcFq8t0=,tag:wxNrsadmpa0cSbDymDkURA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjd3doaFFUY2Z4RVBuY3hN
            SzhxajRWMTZ6TU9ndGx3YUc4Nzg1SVd6Q0JNCnQzdVBMYW5nSUlGU3JJcWhwd1Iv
            dXU4WmZMV2k3L202c1UwQUE5Vk1obEkKLS0tIGlrVG5wSUIrWDFsS1NzZ3NoNG9u
            M21NT0RMSlVNVFJ4dnBEQXFONFdVcjAKw87HETPTRZGPry3Ubaf/vsgkUHsGgU8P
            dpes5CUf1yo53Ch4KNytZc7i83TCjqX0VnDppvsz/vfvKirvheMdOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:26:33Z"
    mac: ENC[AES256_GCM,data:35kPPRrt7JFH2HpyllQQ7r+ySdVroV1FfrOJ0/VnxosGG7eLbiQEHz6atgM4Wo8zO1+Xz3ckfMOfOOLCy5uIJ4x53CcfeukIYpeaxuGtiQOCEFwLdNwEIrZYD6Y+HQh0CcxLOnwTexeFC+E9PjcpzSFdNAZPT+LGlH4BGCnAurA=,iv:kvhNh/g60Uv2zpae9UmY4i/q8vQVLxDA3Ot4gZNaGt8=,tag:CUi/CTxWbfrQvgBSdE6mNQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
