apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:wq1oX1QrUQDk8eMVc9WylY7q2lH3b2JYw3wGlu3qYDE=,iv:26RtCxRZhnCw4T2/vIo9hrPkmIb93eBzZxESpSKn8eo=,tag:Gv7XNIwVP7q7KQmsAzjzgg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFdmd6MU5oaWhPKzBIQklu
            TEZtZGhlVm5QSGNhQ2l0Y21mYW9GYU5CNkd3CkJLd3A1Tm1vbVVFbS9COVZDc1J3
            bU1jVU1XSTBvS1NqQStMY0xnL2tONkkKLS0tIHNHb29KL05yRGFjMEtZYUQva29l
            dkNGaGFYWlEvU21acXp6eHU3eVNyMHcKuBmqzXP6vykjcJCRRhw9wuuk8Hqt6nnY
            qlgHq80Ua5Z4RchZa1sH580ZzJglXQg4m3LjD9IyKW+dIl45FnvvfA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T08:30:08Z"
    mac: ENC[AES256_GCM,data:8xx514K7lD312RZzpLq+mCVTGmyfvZVvYa605S99i8WdUuqy1npSk0rHv2gUrQaMUR/Mpnoda40ya23Mi9KFjRxMYPseV+OkFF/TIzl38EEGWmhSmrhxhSxcvK+tU522lPsNrrBTT6biADNUxR+pnf6obk98Raw6z+EOBcNAIUw=,iv:XV+wqRqW7tcCX4NAowY3qiRqvTMkm85oEPZOf1xwNGY=,tag:yDsRvvIsy/we2vQPhNjNaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
