apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:nbI23fQPDTiz9TR8GJxx7FfUHoTlsCXGjCeJYAk+P6w=,iv:S14OthLuRrhWVlAY75i0MiFtn3qHpGMdIDOz6mGspW4=,tag:ulO7uPwgNQQ0u7b9CYctJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQ3FWNlFjS2RVOGRlNmNJ
            K0M1dExXSnNTR2tRSXVLTlBESnNMcnJSVVRVCk9JYTNWTjBEZitJWFJiMWE1RlNG
            NENvS3liS0xRcEloYTFJSlR1bE14UTQKLS0tIEJKZlhCMkxzYkQxZDFlcWxmbHp2
            MHRhRFByZEtFNTBPdjNPYlBWaXFqbVkKVk7A8RuksA3mTiW0s0YjXYRpS4jWLmKC
            9Ixt4zpQObZR4qzdNPVqEMQvX9gYfCsl591RsRZC4mN/eOqtsZI5kg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-22T10:08:55Z"
    mac: ENC[AES256_GCM,data:XdnL2GwGzvjUzwOcbghh0kAwqsSRurUTjX46BD2zTAIhuT31p3UFSVQg82NCd00Rmy2suNQTfaVnyvEy5tmepId2gKrSZr+4w+mkwX9AaIfhIAsV/LWIUY/z/yjGyd/fCwVzHtW3hi/38lS6W23F1hrodx1DaHsVq/qGzFEGmq4=,iv:Nw9dC5y3zV+xNci13qg6hYfmXuuc/0Ao/LM3kmNIn/0=,tag:jYeaMmA64a8Ps7VFF/koGA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
