---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barman-cloud-client
spec:
  commonName: barman-cloud-client
  duration: 2160h
  isCA: false
  issuerRef:
    name: barman-cloud-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  renewBefore: 360h
  secretName: barman-cloud-client-tls
  usages: ["client auth"]
---
# yaml-language-server: $schema=https://schemas.bykaj.io/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: barman-cloud-server
spec:
  commonName: barman-cloud
  dnsNames: ["barman-cloud"]
  duration: 2160h
  isCA: false
  issuerRef:
    name: barman-cloud-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
  renewBefore: 360h
  secretName: barman-cloud-server-tls
  usages: ["server auth"]
