---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app tdarr-node-amd64
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: tdarr
      namespace: media
  values:
    defaultPodOptions:
      # affinity:
      #   nodeAffinity:
      #     preferredDuringSchedulingIgnoredDuringExecution:
      #     - weight: 1
      #       preference:
      #         matchExpressions:
      #         # Intel N100
      #         - key: feature.node.kubernetes.io/cpu-model.id
      #           operator: In
      #           values:
      #           - "190"
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #       - matchExpressions:
      #         # Intel N100
      #         - key: feature.node.kubernetes.io/cpu-model.id
      #           operator: In
      #           values:
      #           - "190"
      #         - key: intel.feature.node.kubernetes.io/gpu
      #           operator: In
      #           values:
      #           - "true"
      # securityContext:
      #   fsGroup: 1000
      #   fsGroupChangePolicy: OnRootMismatch
      securityContext:
#        runAsUser: 0
#        runAsGroup: 0
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
        supplementalGroups:
          - 44 # video
          - 125 # render
          - 105 # render
          - 568
    controllers:
      tdarr-node-amd64:
        replicas: 3
        strategy: RollingUpdate
        containers:
          node:
            image:
              repository: haveagitgat/tdarr_node
              tag: 2.48.01@sha256:19bd23303defefa77aca01a8bc93abb6dcab685137f74ae0885071a709f4fcd8
            env:
            - name: nodeID
              value: kube-node-amd64
            - name: serverIP
              value: 10.200.15.242
            - name: serverPort
              value: 8266
            resources:
              requests:
                cpu: 100m
                gpu.intel.com/i915: 1
              limits:
                cpu: 2
                gpu.intel.com/i915: 1
    service:
      app:
        controller: *app
        enabled: false
    persistence:
      cache:
        type: nfs
        server: ${NAS_IP:=temp}
        path: "/volume2/piNFS01/flux-cluster/tdarr/cache"
        globalMounts:
          - path: /cache

      dri:
        type: hostPath
        hostPath: /dev/dri

      movies:
        type: nfs
        server: ${NAS_IP:=temp}
        path: /volume2/piNFS01/flux-cluster/media_new/media/Movies
        globalMounts:
          - path: /mnt/movies

      output:
        type: nfs
        server: ${NAS_IP:=temp}
        path: /volume2/piNFS01/flux-cluster/tdarr/output
        globalMounts:
          - path: /output

      tv:
        type: nfs
        server: ${NAS_IP:=temp}
        path: "/volume2/piNFS01/flux-cluster/media_new/media/Recorded TV Shows"
        globalMounts:
          - path: /mnt/recorded-tv

      other-videos:
        type: nfs
        server: ${NAS_IP:=temp}
        path: "/volume2/piNFS01/flux-cluster/media_new/media/Other Videos"
        globalMounts:
          - path: /mnt/other-videos
