---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cloudflare-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        CF_API_TOKEN: "{{ .CF_API_GRAFANA_REPORTING }}"
  dataFrom:
    - extract:
        key: cloudflare
