---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app home-assistant
  namespace: &namespace home
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  dependsOn:
#    - name: cluster-apps-cloudnative-pg-cluster
    - name: external-secrets-stores
      namespace: external-secrets
    - name: volsync
      namespace: volsync
  path: ./kubernetes/apps/home/home-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substitute:
      APP: *app
      APP_UID: "1000"
      APP_GID: "1000"
      VOLSYNC_CLAIM: home-assistant
      VOLSYNC_CAPACITY: 5Gi
#---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: &app home-assistant-code
#  namespace: flux-system
#spec:
#  targetNamespace: home
#  commonMetadata:
#    labels:
#      app.kubernetes.io/name: *app
#  dependsOn:
#    - name: home-assistant
#  path: ./kubernetes/apps/home/home-assistant/code
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: home-kubernetes
#  wait: false
#  interval: 30m
#  retryInterval: 1m
#  timeout: 15m
