---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#  - config-map.yaml
  - helmrelease.yaml
#configMapGenerator:
#  - name: snmp-exporter-synology-nas
#    files:
#      - snmp.yaml=./snmp.yml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
#  labels:
#    grafana_dashboard: "true"
