---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: node-problem-detector
spec:
  interval: 30m
  chart:
    spec:
      chart: node-problem-detector
      version: 2.3.14
      sourceRef:
        kind: HelmRepository
        name: deliveryhero-charts
        namespace: flux-system
      interval: 15m
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: kube-prometheus-stack
      namespace: monitoring
  values:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
      prometheusRule:
        enabled: true
    resources:
      requests:
        cpu: 15m
        memory: 100M
      limits:
        memory: 100M
    settings:
      extraArgs:
      - --event-namespace monitoring
