apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:/XRsHcgLOwnchM3ah4R9,iv:Z0h/+L4teVtlCq+3b57aeIS3FMYvBrecbcwbFDXOb1A=,tag:cAh2TpmLOUa9j4efTKJxDQ==,type:str]
    SVC_MC_ADDR: ENC[AES256_GCM,data:neVIALfNyk+5A18I2g==,iv:mAl4LNNXn46ZQMXnYXULAO1yHqTECJlMIBzcbJftLN8=,tag:mhdNyKCJ0tOKFfBUzbFwLQ==,type:str]
    SVC_MQTT_ADDR: ENC[AES256_GCM,data:uW5tX0q/1hj7xUBIKg==,iv:dAaQmBioPWc3yPCxC4pA8ZxtH0xWlpE4ZgR7/+HschA=,tag:RdmjHicF/5WBLI2A1pXj5w==,type:str]
    PI3B_IP: ENC[AES256_GCM,data:ssPq007QGR91bgvyKg==,iv:fyTd8W8a3zzkrULMO13nYowNRgW76IWHVRz9Ua+8UdI=,tag:TtZ6ScknKlHRhEDzusyJfQ==,type:str]
    SVC_HASS_ADDR: ENC[AES256_GCM,data:dfldbNhIRsC9PjN3Og==,iv:D4uvOvv6R57d/4HjuFCnkF66xf+eZMR9GCYNXySV4XI=,tag:JrRpS2VhM0rkisSQw9US8A==,type:str]
    SVC_PLEX_ADDR: ENC[AES256_GCM,data:tTOYEHx6dXqwzWDrxg==,iv:/EaWuspqIk2K3p9i/21+oncDaPueNTLv+8JPSvPdOdM=,tag:274qjTjfJ1PDqhMHLaSKdQ==,type:str]
    SVC_POSTGRES16_ADDR: ENC[AES256_GCM,data:5FmMbp1UzUbHIHK0QQ==,iv:WnQi2yLpvkJjnU8EpTt2+lWCipir9s1UIx90bwVayV8=,tag:1L6BHarMXW9OdqYyBC13ww==,type:str]
    SVC_POSTGRES17_ADDR: ENC[AES256_GCM,data:K6sOLKxOAbWy/e4gOw==,iv:RlBrwQVjgflDWxoC5jWJjaHD0jI/x4X7TbsNZi9rDrw=,tag:O3FMjgjAuwBwZrvvcXygFA==,type:str]
    SVC_QBITTORENT_ADDR: ENC[AES256_GCM,data:CqgWgIniqV234RIuiw==,iv:kNNd3s3xCKtSdrYjvaMXFsEqnQgMOrCFfmF1HU6Aw7E=,tag:4pcpHiDxfg4NlXgm4ZkiAA==,type:str]
    SVC_LOCALAI_ADDR: ENC[AES256_GCM,data:Q5DnbeoC72hpEBTP/Q==,iv:N5vgGn8AeO1FVcdOQIDP67X+APh2sA2/UcaOKHfKOfg=,tag:zOszI7t9dWYYIcoHs6vcyg==,type:str]
    SVC_SMTP_ADDR: ENC[AES256_GCM,data:tQ2mggg5pd9dhtYuGQ==,iv:KNCiE4Bca2dh83xs0dMJggikDo5iC+kvkl5lU7jUvkU=,tag:4DCqFQu/4yOncyFxnR+kSA==,type:str]
    SVC_UNIFI_ADDR: ENC[AES256_GCM,data:Oynxe82GhAzqPSZFSA==,iv:hF6jMR2YRXVZkoqJbyxsJyJ8uRzfrfV7ieMbClOQIGo=,tag:lQCfevDyNa647POpMlyviw==,type:str]
    SVC_WYOMING_PIPER_ADDR: ENC[AES256_GCM,data:ne1Pc2sfeyWJDypDXA==,iv:LbI4Fo53leTFwKYzwGYU9ZESAEQp1vtOjKfD2vT+gqk=,tag:jLsL2YdV2CiFvpAEWVrMeA==,type:str]
    SVC_WYOMING_WHISPER_ADDR: ENC[AES256_GCM,data:ynH/W0c5+9+s3UrfFg==,iv:oydPWjvyl31MRmj09PQ4FZb1SZ+6VtbMeShsY8LnTeM=,tag:EW6Y8ZXzKBT8kTABoErxtg==,type:str]
    SVC_WYOMING_WAKEWORD_ADDR: ENC[AES256_GCM,data:HM3v5o/9irH2UiwLmQ==,iv:CyfpBkyK+r3SVubO8Ach/gc+/5i4aR1ZJoKOs+adwgE=,tag:dxIHf1IjwnTjJcExsZjn9w==,type:str]
    SVC_FRIGATE_ADDR: ENC[AES256_GCM,data:2z8CmtTNDnjYRnI12w==,iv:TBYGiJduzMI2iPx7XRBRJrluSKfKgW2gY/yGukifepI=,tag:plsb/KIY5E6jhhmfo2z33Q==,type:str]
    SVC_BOINC_ADDR_AMD64: ENC[AES256_GCM,data:UNHlgGV2v9zZ8UnRxQ==,iv:JI4ECdgGp8YlzTwmKYgM79owoYcrTtnPzdJbJfLBMug=,tag:3ZvP/DitPUNjOcbBWBEayQ==,type:str]
    SVC_BOINC_ADDR_ARM64: ENC[AES256_GCM,data:DwZ9bAH8/elv2lChMQ==,iv:KaDHohCRXSFAU89vqXUzu+s5Hs1Gh7LhIM51PCF1xog=,tag:vNANvIKM42UHtmL66F/MOA==,type:str]
    SVC_OLLAMA_ADDR: ENC[AES256_GCM,data:DqaFrBmTyA6XzmKnww==,iv:EuwCQEp1MsS4gU81u4tonYU+fRMeTFNBf+9gMrTS0Zw=,tag:BKSW4JKYXWHpIZlUWUvo9A==,type:str]
    NAS_IP: ENC[AES256_GCM,data:rbtIJqj2+gGyLkhiAA==,iv:CKZ3XODDR1a+diV5Epj2mXJNiR9DSUOwFwUJLpt9ulo=,tag:mJ8Dbw4H4wHEb3fMEAoFqQ==,type:str]
    HASS_PI4: ENC[AES256_GCM,data:C3olSrcmzzmNqdyu6w==,iv:5XmA14ZHmrby9/cGwVZ5O6nrI4jYpcmPHzc+T/Q1PpA=,tag:RbGMajYM3sHowHq2wirVgg==,type:str]
    HASS_YELLOW: ENC[AES256_GCM,data:5dmNp5Qys5niI2SvSg==,iv:/WPDuGMZZeYh3o2yCV4X0oYJscwcrW8lI4T9yCYeg7c=,tag:f+u5DKogOXhhQjp9DoxWbQ==,type:str]
    PIHOLE_IP: ENC[AES256_GCM,data:n/qiMI/kuy+vzlWpLo0=,iv:nNhWndomHa8us8HwqDK2F/e/NlCZF5WFVKbpZk6KphA=,tag:BVG+eaMEz5gMhsOfOFrFZQ==,type:str]
    SVC_PIHOLEK_ADDR: ENC[AES256_GCM,data:o1aCC95Yr2bXdW7u8g==,iv:QrSYndrjtZo380rq6Tb6Hi15GjWDgSSjaHEiZiFd3jw=,tag:gwk1HiNMxwMP2YU9/cc/9g==,type:str]
    SYN_MINIO: ENC[AES256_GCM,data:5b/Nxye6VdVJMFtNElM=,iv:ideYfWGI/++/qVTA5zO/i7opAN1l59OU+7wJtHHoPXI=,tag:uOpL6Isrb8mC8jgo1tG9cQ==,type:str]
    NFS_SERVER_CAMERAS_DIR: ENC[AES256_GCM,data:D57no45KpqrpbzmHP/cSFJs9hptXHKNjb/EuqA6Yqxn+25Lh79eiuHzB/A==,iv:oObTO3xAOwdWWODAvW1rSy7pYrJ6byEosyhkAfIB+UU=,tag:EG3ryZUCDaaT/8vw2QiDng==,type:str]
    SVC_TDARR_ADDR: ENC[AES256_GCM,data:x7EzjYL2qBe4Iqhz+w==,iv:9230fG4PjzSywbZZHCtXM4QVJHBP0VQHdCxMLM1eGBw=,tag:4Lc7m/LKSM++gxu2eTdh+w==,type:str]
    TIMEZONE: ENC[AES256_GCM,data:8xnGpyM3dNSRnxbqIfFNXcpZiQ==,iv:gbJ1Ziuc8j/tqN/xO5ExkRJqAE6Hua+EHtXIhCtXMeI=,tag:4bcOMMkWFOwArMZqxOE0xA==,type:str]
    SVC_SYSLOG_ADDR: ENC[AES256_GCM,data:R8KvBSPyu7GPKQzhVg==,iv:VHsJRTonsx5wQ+yDYVH2OWfSdd+47hoIAW0G0uyY5f8=,tag:tXoze3UMaeInJdjPTmrYiA==,type:str]
    SVC_SYSLOG_IDS_ADDR: ENC[AES256_GCM,data:v+Gl881HTakC8GcwmQ==,iv:71MUNn1WuCZc8vdQL4bD+Cmbhg1/tiOkHMMHo1LUCPc=,tag:sUQ95kGrTKgeIZaG0Fc1Tw==,type:str]
sops:
    age:
        - recipient: age1tcah38ehyckvyd20eg8x874sl58clvf9w6y60p3qqxykaatwq33s6sealk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4aERublVSeVVuNU9td1Va
            NHZBSlFna05ZNUZncDlqZ2tnTFRrNUt4T1NNCklSUExVQXVjVFJOYzhwaEw4aUJo
            VjdtWVlpSllQZVdCL2hnTGRCYks5KzQKLS0tIGE4M2ZnVjdLTGJ3alRYTGN1U1JT
            bitBVHZia3c5Yk42Z3Y1SzU5dGVHWUkKleP6IjIQazlzbBCVeuzX9A+eyN7VAFUx
            tq1zKw/PECInizzS+QKGQgIPv8IoLmz1o47o6d44FipJtKUw8//d8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-30T09:43:30Z"
    mac: ENC[AES256_GCM,data:qLfJgDZf9v/Z2d2L7GJfzvDbngBJkVQXvQUbgJqmghbNFyiCnRb6jb/USQu7UokUvhxy4vLzQkrBDaLTnK6fpzwwnaDUoUtgXAhhm8N40xPUQEUtuoyFBhNabNXTJrXra9g2cseoLp4Ejtj78E+G182jchVQMdkfR+Yi1IgBz34=,iv:PsNyVs5sLv38K+sskdlKJ6Z7JoKLQRIp9gTvMNJGkt4=,tag:F5zBOHtx1p4szXDY0bkSag==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
