apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Jqxvl2rIryjfy18KY4px,iv:TyWmCZImnKx2houfOXh7IADyI47MSiw/qxNmZPWzdss=,tag:JlqPs9cT+/W5JHnxThy6JQ==,type:str]
sops:
  age:
    - recipient: age1tcah38ehyckvyd20eg8x874sl58clvf9w6y60p3qqxykaatwq33s6sealk
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2cnlpZlRyem0vRHZZSXZI
        d0huRUZIb0ttWXVOdEM2ZkdJSnk0RTRPTVFzCkFRNjdqVFMydWxTR2dtYi9CV29F
        ZmNIVUk5RkdKWi8wTWZqZGtINWJwcmcKLS0tIDFuOGxaWEwyeUk3NytJS3ZrbWJW
        STN1endOSWpsUEFhZ01zWGlBcC9qQ0UKTQ9XWJ7dXYuTzTYZfwBOB2hAnB9nqjVw
        a7ys+lN7zJwsaBQ/d3bnl4BACvezLTE/8Fmot0lrfLpkOb5/p/Oj2g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-27T17:27:35Z"
  mac: ENC[AES256_GCM,data:Rbhi1tWkr5DP6pZASefHBNYtbc5GWpPdTdUj2VmLa0pRSUTlZsXJUyYajVyJqsWKIdgK+En+ZtF/NpFipa+kaLwnMaHNr65TDlW724KcUQdGlSMdbOxb6O38B09keUjPEh0z3ocMgHcd+BAgC4hKs3AZVZvek8LWI4J1xtHydxY=,iv:PFkgZzGTkHL70CoqJzU9+YXys9xUtKp3RxxLJvDjSWs=,tag:afjyR4SQhwv6go8Zvmmcaw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
