apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:YPOmNShCD8zMSip6QYZSS0hL2phtqUpZ0eCOoadG0kEBevtzapksPg==,iv:9EhzmSHjfdFV+9u0HLEWG2wujuwAhIyM1UTL7mpzBtQ=,tag:ShppAh8+MsosL6wt+IK+Cw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYkxxSlVXZ3Z1Sm5TNW43
            R0RCSGpDSTdkeTF6UHhtS0xxeUs4bDVQNVdVCmNJYzA4T3pFN1NqME1uYlZ6Y3lT
            YnQzU09GVXFHdVN1YVMxai91OXgyaWcKLS0tIGtmWVdjdEQwWW9wcjQ0NzVYZEp2
            VEpqTzdmQ1daTzM2VllhNFpOZGVLNTgKFeNeXhbbhtZZg7MMkzHdWKLudDb7bYWI
            7G2j5227l7XBmmUX3439/GyG/Bk2FiwAmOgQPNyRwlNzDpDCAgiyBw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:58:23Z"
    mac: ENC[AES256_GCM,data:MlbTROSs+v0c/lP6kMZYn5MQ9YiAJtQm2PZ64q6QtOFgvbXo0CD7/6wvVky0eb8R5wY0AkIF6WCo+wPTZTgRYTJIhu7jKJZ8qbXlNIpmRCYbA1rFKaGRDt+afPMHx5hLGQy79i0iZw3m6burV+umG2TYmaHX5qIolxL0xGy3+hU=,iv:Rk0alH8oBKbNSZeLnYnsEiUq4qFOIndxd2Lg2sf1PXA=,tag:ebEAv2l3vi4krN1/1D3plQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
