apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:/sMTiQtJsfIFlxMOVQ71FN4o7yhCfyE6TLLaXMAmjm75BJaoyOFGog==,iv:c3Yh1FSAcD+8CbuDLlJ1DlPlPKN+BKMIsatJbHYCMYc=,tag:zZHQb2HS8x5ke9cQcSE7Jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkdElvUzFidXhTZlJKeHNP
            WUpkOHEvM3phUXBRSTlqRG1BaHVDVHlGM1RzCkNEOGVwSThydVg4U1R3WHdvWUgx
            clhiNU43RDcwamQvVlFPWmthdjNrY00KLS0tIE82THp4UWNuY3dOeEpRWSs3U0Ir
            ZENvN1dZMUdoTXZ6ZVNxWERudTNIUFEKbZRXm6Sw+cwg/CWRauPd0MazrRRstPqe
            ItFoTtvJ27D2wSSgpySXo/KuDbg0aRN0hNJvF/U8kVWgykQTG7h5IA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:26:33Z"
    mac: ENC[AES256_GCM,data:ZEkNNiqlB/xx1CEQOSHx/jDZ0tgl84GC9bubUEj3rtE5X5yjcGXl1wNf+XjsgYMiFkFlY5LvnN4GLDQLBYivnTSQ9tU84V1ik0zBoHdH5wyxCpecnDnRGFw2AXegbBcadegwerTSuoLy/PegaUmg5elx1C/+aPdcg0fRTQ9eqCA=,iv:EdJDSJpzTRQ+uvfXZLpG5mR83MTuo81buv8zU6vTcrc=,tag:SMRnUc9v5xRfq/Sl+48cDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
