apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:kei6U7AlZeXpT2pLztvPFo3AKJoYNVn/9hkQEYDL9gV1iW8MQIipyQ==,iv:bzTGrO4UjHQMbhEMzPm+ex43fJxVynjuyIggwRiuIV4=,tag:2ZZMHgN7E2rZFbawUF814w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1572xu3arfwfwe4dslcpld4nez98zrqwszalkq2n56y5yzlcqaulsl2tw4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBremFmdUx0d1lmdlQrZWoy
            L2FKVVlzOEExc3p4QnNtZVJ2ekhaWHh3LzM0ClpVY2k0Qk80OGJlbzJEallDeTJk
            eE9KckUvTm9CNWYrU1hUYVluL2Uwa0UKLS0tIENQcEV6RlRvV3JsVXpvS05xaHNj
            Nk5oZ245TzN5MjFaZ291RzNUcE9sVFkKQ8j9APKThJ1LGBCNGsiE9Po5qE7jwk8f
            sEz+d4SuNMxmBBl1m5NSUUH045PyYhOuTmJwAAoNBZcXlMMvqGRqCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-25T11:45:42Z"
    mac: ENC[AES256_GCM,data:jpQpl4ligiTou7m2h4ZQNGBBvasra4w3xHisIJK01pI97FVuTq8DuRElzuLDvqd2TrkE8xOt9pi1gGzEYfAKJww8Q2vhwxHhM+wGU1VCOQeO4Pk5sZetbPJ0SodxokW9Cbp/iMvWkMJDDCBv7evDMBOl2fwrhPq/YtxZmc7wGxM=,iv:xeHjA0t0nTevEfBbLYKbar8/2P1z2aS1K8wchgfwjl8=,tag:+uL4X9wfPontZ0oc+ISR2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
