---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: pve-exporter-secret
    template:
      engineVersion: v2
      data:
        # App
        PVE_USER: "{{ .PVE_EXPORTER_USER }}"
        PVE_PASSWORD: "{{ .PVE_EXPORTER_PASSWORD }}"
        PVE_TOKEN_NAME: "{{ .PVE_EXPORTER_TOKENID }}"
        PVE_TOKEN_VALUE: "{{ .PVE_EXPORTER_TOKEN2 }}"
        PVE_VERIFY_SSL: "false"
  dataFrom:
    - extract:
        key: proxmox
