---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
#  - ./gatus.yaml
# Volsync disabled need to change to PVCs
#  - ./volsync_backblazeb2.yaml
#  - ./volsync_nas.yaml
