---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: open-webui
  namespace: ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: open-webui-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ## Authentik Auth
        OAUTH_CLIENT_ID: "{{ .OPENWEBUI_OAUTH_CLIENT_ID }}"
        OAUTH_CLIENT_SECRET: "{{ .OPENWEBUI_OAUTH_CLIENT_SECRET }}"
        OPENID_PROVIDER_URL: "{{ .OPENWEBUI_OPENID_PROVIDER_URL }}"
        OPENID_REDIRECT_URI: "{{ .OPENWEBUI_OPENID_REDIRECT_URI }}"
        # App
        DATABASE_URL: "postgresql://{{ .POSTGRES_USER }}:{{ .POSTGRES_PASS }}@postgres17-rw.database.svc.cluster.local.:5432/openwebui?sslmode=disable"
        # Postgres Init
        INIT_POSTGRES_DBNAME: openwebui
        INIT_POSTGRES_HOST: postgres17-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # Redis
        # https://docs.openwebui.com/getting-started/advanced-topics/env-configuration/#redis
#        ENABLE_WEBSOCKET_SUPPORT: "true"
#        WEBSOCKET_MANAGER: "redis"
#        WEBSOCKET_REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/7"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: open-webui
