---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app plex
  namespace: &namespace media
spec:
  targetNamespace: *namespace
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../flux/components/volsync
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
    - name: intel-device-plugin-gpu
      namespace: kube-system
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync
  path: ./kubernetes/apps/media/plex/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CLAIM: plex-config-0
      VOLSYNC_CAPACITY: 5Gi
#---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cluster-apps-plex-auto-languages
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: cluster-apps-external-secrets-stores
#  path: ./kubernetes/apps/media/plex/auto-languages
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: home-kubernetes
#  wait: false
#  interval: 30m
#  retryInterval: 1m
#  timeout: 5m
#---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: cluster-apps-plex-off-deck
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: cluster-apps-external-secrets-stores
#  path: ./kubernetes/apps/media/plex/off-deck
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: home-kubernetes
#  wait: false
#  interval: 30m
#  retryInterval: 1m
#  timeout: 5m
